[mausoleum-signer-dragons]
id = 900003100
name = "Mausoleum of the Signer Dragons"
type = "spell field"
effect = """
When this card is activated: You can add 1 Spell/Trap that mentions "The Crimson Dragon" from your Deck to your hand, except "{CARD_NAME}". \
Special Summons of your Dragon Synchro Monsters cannot be negated. \
Neither player can return your Dragon Synchro Monster that mentions a Synchro Monster as material from the field to the Extra Deck. \
If you Synchro Summon a Dragon monster: You can draw 1 card. \
If a Dragon Synchro Monster(s) you control leaves the field by your card effect, or to activate the effect of your card: \
    You can Special Summon 1 of those monsters. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
If this card in its owner's control is destroyed by an opponent's card effect: \
    You can Special Summon 1 "The Crimson Dragon" from your Extra Deck. \
"""
strings = [
    "1 Spell/Trap that mentions \"The Crimson Dragon\"?",
    "Draw 1 card",
    "Special Summon the leaved monster",
]

[red-dragonator-archfiend]
id = 900003101
alias = 70902743
name = "Red Dragonator Archfiend"
type = "monster synchro effect"
attribute = "dark"
race = "dragon"
level = 8
atk = 3000
def = 2000
effect = """
1 Tuner + 1+ non-Tuner monsters
(This card's name is always treated as "Red Dragon Archfiend".)
Once per turn, during your Main Phase 1: \
    You can destroy as many face-up Attack Position monsters on the field as possible with ATK less than or equal to this card's (other than this card). \
    Other monsters cannot attack the turn you activate this effect. \
After damage calculation, if this card attacked an opponent's Defense Position monster: \
    Destroy all Defense Position monsters your opponent controls. \
"""
strings = [
    "Affected by effect \"{CARD_NAME}\": other monsters cannot attack this turn",
    "Destroy monster with ATK less than or equal to this card's",
    "Destroy all your opponent's defense position monsters",
]

[stardust-crimson-dragon]
id = 900003102
alias = 44508094
name = "Stardust Crimson Dragon"
type = "monster synchro tuner effect"
attribute = "wind"
race = "dragon"
level = 8
atk = 2500
def = 2000
effect = """
1 Tuner + 1+ non-Tuner monsters
(This card's name is always treated as "Stardust Dragon" and non-Tuner Monter)
When another card or effect is activated \
    that targets, or would destroy, a card(s) on the field (Quick Effect): \
    You can Tribute this card; negate the activation, and if you do, destroy it. \
    During the End Phase, if this effect was activated this turn (and was not negated), \
    Special Summon this card from your GY. \
"""
strings = ["Negate the activation"]

[black-winged-crimson-dragon]
id = 900003103
alias = 9012916
name = "Black-Winged Crimson Dragon"
type = "monster synchro effect"
attribute = "dark"
race = "dragon"
level = 8
atk = 2800
def = 1600
effect = """
1 Tuner + 1+ non-Tuner monsters
(This card's name is always treated as "Black-Winged Dragon".)
If you would take damage from a card effect, place 1 Black Feather Counter on this card instead. \
If you take damage from an attack not involving this card, place 1 Black Feather Counter on this card. \
This card gains 100 ATK for each Black Feather Counter on it. \
Once per turn: You can target 1 face-up monster your opponent controls; \
    the target loses 700 ATK for each Black Feather Counter on this card, \
    and if it does, remove all Black Feather Counters on this card \
    and inflict damage to your opponent equal to that lost ATK. \
    This is a Quick Effect if this card has 4 or more Black Feather Counter on it. \
"""
strings = ["Remove counter to down ATK and inflict damage"]

[black-rose-crimson-dragon]
id = 900003104
alias = 73580471
set = "rose-dragon"
name = "Black Rose Crimson Dragon"
type = "monster synchro effect"
attribute = "fire"
race = "dragon"
level = 8
atk = 2400
def = 1800
effect = """
1 Tuner + 1+ non-Tuner monsters
(This card's name is always treated as "Black Rose Dragon".)
If this card is Summoned: You can destroy any number of cards you control, \
    and if you do, destroy the same number of cards your opponent controls. \
Once per turn: \
    You can target 1 Tuner or Plant monster that is banished or in your GY, and 1 face-up monster your opponent controls; \
    shuffle the first target into the Deck, and if you do, \
    the second target's ATK/DEF becomes half its current ATK/DEF until the End Phase. \
"""
strings = ["Destroy cards on the field", "Halve ATK/DEF of 1 monster"]

[ancient-fairy-crimson-dragon]
id = 900003105
alias = 25862681
name = "Ancient Fairy Crimson Dragon"
type = "monster synchro effect"
attribute = "light"
race = "dragon"
level = 8
atk = 2100
def = 3000
effect = """
1 Tuner + 1+ non-Tuner monsters
(This card's name is always treated as "Ancient Fairy Dragon".)
You can Special Summon 1 Level 4 or lower monster from your hand, \
    but that monster cannot attack this turn. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
Once per turn: You can destroy as many Field Spells on the field as possible (min. 1), \
    and if you do, gain 1000 LP for each destroyed cards, \
    then you can add 1 Field Spell from your Deck or GY to your hand. \
Once per turn, after resolving a Field Spell that was activated during your turn: \
    This card gain 1000 ATK until the end of your opponent's turn. \
"""
strings = [
    "Special Summon 1 Level 4 or lower monster",
    "Destroy Field Spells",
    "Add 1 Field Spell to your hand?",
]

[life-stream-crimson-dragon]
id = 900003106
alias = 25165047
name = "Crimson Life Stream Dragon"
type = "monster synchro tuner effect"
attribute = "earth"
race = "dragon"
level = 8
atk = 2900
def = 2400
effect = """
1 Tuner + 1+ non-Tuner monsters
(This card's name is always treated as "Life Stream Dragon".)
If this card was Synchro Summoned using a Synchro Monster as material: You can make your LP become 8000. \
After this card is Special Summoned, you take no effect damage until the end of your opponent's turn. \
Once per turn: You can discard 1 card; add 1 Equip Spell from your Deck or GY to your hand. \
Once per turn: You can declare a Level from 1 to 12; \
    all other Synchro Monsters you currently control become that Level until the end of this turn. \
"""
strings = [
    "Make your LP become 8000",
    "Affected by effect \"{CARD_NAME}\": take no effect damage",
    "Add 1 Equip Spell to your hand",
    "Change Level of other Synchro Monsters",
]

[majestic-black-dragon]
id = 900003107
set = "majestic"
name = "Majestic Black Dragon"
type = "monster synchro effect"
attribute = "dark"
race = "dragon"
level = 10
atk = 3900
def = 2600
effect = """
"Majestic Dragon" + "Black-Winged Dragon" + 1 non-Tuner monster
Each time another monster effect is activated, \
    place 1 Black Feather Counter on this card immediately after it resolves, \
    and if you do, inflict 700 damage to them. \
(Quick Effect): You can Tribute this card with 4 or more Black Feather Counters; \
    banish all cards your opponent controls. \
Once per turn: You can target 1 face-up monster your opponent controls; \
    negate its effects until the end of this turn, \
    and if you do, inflict damage to your opponent equal to the ATK of that target. \
{MAJESTIC_RETURN|Black-Winged Dragon} \
"""
strings = [
    "Return this card to Special Summon 1 \"Black-Winged Dragon\"",
    "Tribute to banish your opponent cards",
    "Negate effect & Inflict damage",
]


[majestic-rose-dragon]
id = 900003108
set = "majestic rose-dragon"
name = "Majestic Rose Dragon"
type = "monster synchro effect"
attribute = "fire"
race = "dragon"
level = 10
atk = 3750
def = 2800
effect = """
"Majestic Dragon" + "Black Rose Dragon" + 1 non-Tuner monster
If this card is Synchro Summoned: You can banish all cards from your opponent's GY face-down. \
If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent. \
Once per turn: You can target 1 face-up monster your opponent controls; \
    negate its effects, and if you do, change its ATK and DEF to 0. \
    These changes last until the end of this turn. \
{MAJESTIC_RETURN|Black Rose Dragon} \
"""
strings = [
    "Return this card to Special Summon 1 \"Black Rose Dragon\"",
    "Banish all cards from your opponent's GY face-down",
    "Negate effect & Make ATK/DEF become 0",
]

[majestic-fairy-dragon]
id = 900003109
set = "majestic"
name = "Majestic Fairy Dragon"
type = "monster synchro effect"
attribute = "light"
race = "dragon"
level = 10
atk = 3600
def = 4000
effect = """
"Majestic Dragon" + "Ancient Fairy Dragon" + 1 non-Tuner monster
This card gains ATK equal to the difference between your LP and your opponent's. \
Once per turn, during your Main Phase 1: \
    You can Special Summon 1 Level 8 or lower monster from your hand or in either GY, \
    but it cannot attack this turn. \
Once per turn: You can target 1 face-up monster your opponent controls; \
    negate its effects until the end of this turn, and if you do, gain LP equal to its ATK. \
{MAJESTIC_RETURN|Ancient Fairy Dragon} \
"""
strings = [
    "Return this card to Special Summon 1 \"Ancient Fairy Dragon\"",
    "Special Summon 1 Level 8 or lower monster",
    "Negate effect & Recover LP",
]

[majestic-life-dragon]
id = 900003110
set = "majestic"
name = "Majestic Life Dragon"
type = "monster synchro tuner effect"
attribute = "earth"
race = "dragon"
level = 10
atk = 3950
def = 3400
effect = """
"Majestic Dragon" + "Life Stream Dragon" + 1 non-Tuner monster
If this card is Special Summoned: \
    You can equip up to 3 Equip Spells with different names from your hand, Deck and/or GY to this card, \
    and if you do, your opponent cannot target those cards with card effects, \
    also they cannot be destroyed by your opponent's card effects. \
Any effect that would inflict damage to you makes you gain that much LP, instead. \
Once per turn: You can target 1 face-up monster your opponent controls; \
    negate its effects until the end of this turn, \
    and if you do, you can change its battle position. \
{MAJESTIC_RETURN|Life Stream Dragon} \
"""
strings = [
    "Return this card to Special Summon 1 \"Life Stream Dragon\"",
    "Equip Spells to this card",
    "Negate effect & Change position",
    "Change position?",
]


[shooting-stardust-dragon]
id = 900003111
set = "stardust"
name = "Shooting Stardust Dragon"
type = "monster synchro effect"
attribute = "wind"
race = "dragon"
level = 10
atk = 3300
def = 2500
effect = """
1 Tuner Synchro Monster + 1 non-Tuner Synchro Monster
Once per turn, during the Main Phase, you can (Quick Effect): Immediately after this effect resolves, \
    Synchro Summon this card from your Extra Deck using monsters you control, including "Stardust Dragon". \
    Your opponent cannot activate cards or effects in response to this effect's activation. \
Once per turn: You can excavate the top 5 cards of your Deck, shuffle them back in, \
    also this card gains 1 additional attack each Battle Phase for every Tuner monsters excavated. \
Once per turn, when another card or effect is activated \
    that targets, or would destroy, a card(s) on the field (Quick Effect): \
    You can negate that effect, and if you do, destroy it. \
Once per turn, during your opponent's turn, \
    when your opponent activates a card or effect, or when an opponent's monster declares an attack (Quick Effect): \
    You can banish this card, and if you do, you can negate 1 attack this turn from a monster your opponent controls. \
    During the next End Phase, Special Summon this card banished by this effect. \
"""
strings = [
    "Excavate Tuner to gain multi-attack",
    "Negate the effect",
    "Banish this card until the end phase",
    "Do you want negate the attack by effect of \"{CARD_NAME}\"?",
]

[shooting-cosmic-quasar-dragon]
id = 900003112
rarity = "gold"
name = "Shooting Cosmic Quasar Dragon"
type = "monster synchro effect"
attribute = "light"
race = "dragon"
level = 12
atk = 4000
def = 4000
effect = """
1 Tuner Synchro Monster + 2+ non-Tuner Synchro Monsters
Must be Synchro Summoned. \
This card's Synchro Summon and its effect activations and its effects cannot be negated. \
After this card is Synchro Summoned, place Cosmic Counters on this card \
    equal to the number of original Dragon Synchro Monsters used as its Synchro Material. \
Cannot be Tributed, or used as material for an Summon. \
Unaffected by other monsters' effects. \
When another card or effect is activated (Quick Effect): \
    You can remove 1 Cosmic Counter from this card; \
    negate that effect, and if you do, destroy 1 other card on the field. \
If this card battles an opponent's monster, \
    negate the effects of that monster during the Damage Step only. \
At the end of the Damage Step, if this card attacked, \
    you can remove 1 Cosmic Counter from this card, \
    and if you do, this card can attack gain. \
Once per turn, during the End Phase, place Cosmic Counters on this card \
    until it has equal to the number of original Dragon Synchro Monsters used as its Synchro Material. \
When this face-up card leaves the field, you can Special Summon 1 Level 11 or lower Dragon Synchro Monster \
    that is banished, or in your Extra Deck, GY. (This Special Summon is treated as a Synchro Summon.) \
"""
strings = [
    "Negate the effect & Destroy 1 card on the field",
    "Remove Cosmic Counter to attack again?",
    "Special Summon 1 Dragon Synchro Monster?",
]

[mark-of-the-dragon-star]
id = 900003120
name = "Mark Of The Dragon Star"
type = "spell"
effect = """
Activate 1 of these effects. This effect's activation and effect cannot be negated.
● Shuffle 1 Tuner from your hand or GY into the Deck, then draw 2 cards.
● Special Summon from your Extra Deck, \
    1 "Power Tool" Synchro Monster or 1 Level 7 or 8 Dragon Synchro Monster, \
    except a monster that mentions a Synchro Monster as material, \
    but it cannot attack or activate its effects this turn, \
    also for the rest of this turn, you cannot Special Summon monsters from the Extra Deck, except Synchro Monsters. \
    (This Special Summon is treated as a Synchro Summon.)
If your Synchro Monster(s) you control is destroyed by your opponent's attack or card effect while this card is in your GY: \
    You can shuffle 1 card that mentions "The Crimson Dragon" is banished or in your GY into the Deck; \
    Special Summon 1 "The Crimson Dragon" from your Extra Deck. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = [
    "Shuffle Tuner into the Deck",
    "Summon a Synchro Monster",
    "Affected by effect \"{CARD_NAME}\": cannot Special Summon from the Extra Deck, except Synchro Monsters",
]

[void-eyes-infernity-dragon]
id = 900003199
set = "void infernity"
name = "Void-Eyes Infernity Dragon"
type = "monster synchro effect"
attribute = "dark"
race = "dragon"
level = 8
atk = 3000
def = 3000
effect = """\
1 DARK Tuner + 1+ non-Tuner Fiend monsters
Once per turn, when your opponent activates a card or effect while you have no cards in your hand (Quick Effect): \
    You can negate the activation, and if you do, destroy it, \
    and if you do, this card gains 500 ATK. \
If your LP becomes 0 while you have no cards in your hand: \
    You can Special Summon this card (from your Extra Deck or GY). \
    Your opponent cannot activate cards or effects in response to this effect's activation. \
If this card is Special Summoned this way, gain these effects;
● You cannot lose the Duel. If this card leaves the field, you lose the Duel.
● Cannot be Tributed, or used as material for an Summon. \
    Control and battle position of this card cannot change by card effects. \
    The above effects cannot be negated.
● While face-up on the field, this card gains the effects of all "Infernity" monsters in your GY, \
    except "{CARD_NAME}".
"""
strings = [
    "Negate the activation & gain 500 ATK",
    "Open the Zero Gate of the Void",
]
