[blue-eyes-legend-dragon]
id = 900000200
alias = 89631139
set = "blue-eyes"
name = "Blue-Eyes Legend Dragon"
type = "monster normal"
attribute = "light"
race = "dragon"
level = 8
atk = 3000
def = 2500
effect = """\
(This card's name is always treated as "Blue-Eyes White Dragon".)
You can Special Summon this card (from your hand) by \
    revealing 1 Level 1 LIGHT Tuner in your hand. \
    You can only Special Summon "{CARD_NAME}" once per turn this way. \
If this card attacks a monster, before damage calculation: \
    You can destroy that monster. \
"""
strings = ["Destroy battling monster"]

[blue-eyes-divine-dragon]
id = 900000201
set = "blue-eyes"
name = "Blue-Eyes Divine Dragon"
type = "monster fusion effect"
attribute = "light"
race = "dragon"
level = 12
atk = 4500
def = 3800
effect = """\
"Blue-Eyes White Dragon" + "Blue-Eyes White Dragon" + "Blue-Eyes White Dragon"
A Fusion Summon of this card can only be done with the above materials. \
Your opponent cannot target or destroy this card with card effects. \
Once per turn: You can target up to 3 other cards on the field; destroy them. \
    This card cannot attack the turn this effect is activated. \
If this card attacks, your opponent cannot activate cards or effects until the end of the Damage Step. \
At the end of the Damage Step, if this Fusion Summoned card attacked: \
    This card can make a second and third attack during each Battle Phase this turn. \
    Other monsters cannot attack during the turn you activate this effect. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = [
    "Destroy up to 3 cards",
    "Make second and third attack",
    "Can make a second and third attack",
]

[blue-eyes-holy-dragon]
id = 900000202
set = "blue-eyes"
name = "Blue-Eyes Holy Dragon"
type = "monster synchro effect"
attribute = "light"
race = "dragon"
level = 9
atk = 3000
def = 2500
effect = """\
1 Tuner + 1 non-Tuner "Blue-Eyes" monster
Except the turn this card was sent to the GY, you can Special Summon this card (from your GY) \
    by Tributing 1 "Blue-Eyes White Dragon" you control. \
    You can only Special Summon "{CARD_NAME}" once per turn this way. \
After this card is Special Summoned, until the end of the next turn, \
    Dragon monsters you currently control cannot be destroyed by card effects. \
Gains 300 ATK for each Dragon monster in your GY. \
When your opponent activates a card or effect that targets a "Blue-Eyes" monster(s) you control (Quick Effect): \
    You can negate that effect. \
You can Tribute this card; \
    negate the effects of 1 other face-up card on the field, also destroy it. \
    Your opponent cannot activate cards or effects in response to this effect's activation. \
"""
strings = ["Negate & destroy card on the field"]

[blue-eyes-deep-dragon]
id = 900000203
set = "blue-eyes"
name = "Blue-Eyes Deep Dragon"
type = "monster xyz effect"
attribute = "light"
race = "dragon"
rank = 8
atk = 0
def = 0
effect = """\
2 Level 8 "Blue-Eyes" monsters
You can also Xyz Summon this card by using 1 "Blue-Eyes White Dragon" you control as the material. \
If this card is Special Summoned, attach 1 Dragon monster in your GY to this card, \
    then this card's original ATK becomes equal to the ATK of the material monster attached to it with the highest ATK. \
    This effect cannot be negated. \
If a face-up "Blue-Eyes" monster(s) you control is destroyed by battle or card effect, \
    except "{CARD_NAME}": You can Special Summon this card from your GY. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
If a "Blue-Eyes" monster(s) you control would be destroyed by card effect, \
    you can detach 1 material from this card instead. \
If this card on the field is destroyed by card effect: \
    You can destroy all monsters your opponent controls, and if you do, \
    inflict 600 damage to your opponent for each Dragon monster with different names in your GY, except this card. \
"""
strings = ["Xyz Summon by using \"Blue-Eyes White Dragon\""]

[blue-eyes-chaos-infinity-dragon]
id = 900000204
set = "chaos blue-eyes"
name = "Blue-Eyes Chaos Infinity Dragon"
type = "monster link effect"
attribute = "light"
race = "dragon"
link = 4
link-arrow = "left bottom-left bottom-right right"
atk = 4000
effect = """\
3+ monsters, including an "Blue-Eyes" monster
Must be Link Summoned. \
You can also Link Summon this card by sending 1 Ritual Spell from your hand or Set on your field \
    and using 1 "Blue-Eyes White Dragon" you control as the material. \
Your opponent cannot target or destroy this card with card effects. \
If this card was Link Summoned using a "Blue-Eyes White Dragon", when it declares an attack: \
    You can change the battle positions of as many monsters your opponent controls as possible, \
    and if you do, the ATK/DEF of those changed monsters become 0. \
If this card attacks a Defense Position monster, inflict double piercing battle damage to your opponent. \
"""
strings = ["Link Summon by using \"Blue-Eyes White Dragon\""]
