[photon-world]
id = 900003100
name = "Photon World"
set = "photon galaxy"
type = "spell field"
effect = """
(This card is always treated as a "Galaxy" card.)
You can only activate 1 "{CARD_NAME}" per turn. \
When this card is activated: Place underneath this card, \
    1 "Photon" Continuous Spell/Trap from your hand or Deck. \
If you activated a Continuous Spell/Trap while you control a "Galaxy" Dragon monster, \
    you can place that card underneath this card when that card resolves. \
This card gains the original effects of all Continuous Spell/Trap(s) underneath it. \
"""
strings = ["Place the activated card underneath this card?"]
