[photonized-galaxy-world]
id = 900003100
name = "Photonized Galaxy World"
set = "photon galaxy"
type = "spell field"
effect = """
You can only activate 1 "{CARD_NAME}" per turn. \
When this card is activated: Place underneath this card, \
    1 "Photon" Continuous Trap from your hand or Deck, \
    and if you do, you can add 1 "Galaxy" Continuous Spell from your Deck or GY to youd hand. \
If you activated a "Photon" or "Galaxy" Continuous Spell/Trap, \
    you can place that card underneath this card when that card resolves. \
This card gains the original effects of all Field Spells and Continuous Spell/Trap(s) underneath it. \
Xyz Summons of your Xyz Monsters cannot be negated. \
"""
strings = [
    "Add 1 \"Galaxy\" Continuous Spell youd hand?",
    "Place the activated card underneath this card?",
]

[galaxy-eyes-luminous-dragon]
id = 900003101
alias = 93717133
name = "Galaxy-Eyes Luminous Dragon"
type = "monster effect"
attribute = "light"
race = "dragon"
level = 8
atk = 3000
def = 2500
effect = """\
(This card's name is always treated as "Galaxy-Eyes Photon Dragon".)
You can Special Summon this card (from your hand) by Tributing 2 LIGHT monsters with 2000 or more ATK. \
During the Battle Step, if this card battles an opponent's monster (Quick Effect): \
    You can target that opponent's monster; banish both this card from the field and that target. \
    Return those banished monsters to the field at the end of the Battle Phase, \
    and if you do, your opponent's monster effects are negated. \
"""
strings = ["Banish both this card from the field and that target"]

[galaxy-eyes-full-armor-luminous-dragon]
id = 900003102
name = "Galaxy-Eyes Full Armor Luminous Dragon"
set = "photon galaxy-eyes"
type = "monster xyz effect"
attribute = "light"
race = "dragon"
rank = 8
atk = 3000
def = 2500
effect = """\
2 Level 8 LIGHT monsters
You can also Xyz Summon this card by using a "Galaxy-Eyes" Dragon monster you control as material. \
"""
strings = ["Xyz Summon by using a \"Galaxy-Eyes\" Dragon monster"]

[neo-galaxy-eyes-dark-matter-dragon]
id = 900003110
name = "Number C95: Neo Galaxy-Eyes Dark Matter Dragon"
set = "number-c chaos galaxy-eyes"
type = "monster xyz effect"
attribute = "dark"
race = "dragon"
rank = 10
atk = 5000
def = 0
effect = """\
4 Level 10 DARK monsters
You can also Xyz Summon this card by using a "Galaxy-Eyes" Xyz Monster you control as material. \
    (Transfer its materials to this card.) \
Cannot be used as material for an Xyz Summon. \
Your opponent cannot target this card with card effects. \
Once per turn: You can send 1 monster from your Deck to the GY; \
    attach 1 Dragon monster from your Extra Deck or GY to this card as material, \
    then you can banish 1 card your opponent controls or from their GY, face-down. \
If this card has a DARK Dragon Xyz Monster as material, it gains this effect.
● You can detach 1 material from this card; this card can make up to 3 attacks on monsters during each Battle Phase this turn.
● If this card destroys an opponent's monster by battle, attach that monster to this card as material.
"""
strings = [
    "Xyz Summon by using \"Galaxy-Eyes\" Xyz Monster",
    "Send 1 monster to the GY then attach Dragon monster",
    "Banish 1 card your opponent controls or from their GY, face-down?",
    "Detach 1 material to make up to 3 attacks on monsters",
    "Can make up to 3 attacks on monsters",
]

[photon-stream-eternity]
id = 900003111
name = "Photon Stream of Eternity"
set = "photon"
type = "spell quick-play"
effect = """
If you control a "Galaxy-Eyes" Xyz Monster: banish all Spell/Trap cards your opponent controls, \
    then, if you control "Number 62: Galaxy-Eyes Prime Photon Dragon" or a Xyz Monster that mentions it, \
    negate the effects of all face-up monsters your opponent controls (if any). \
You can only activate this card during your turn, unless you control \
    "Number 62: Galaxy-Eyes Prime Photon Dragon" or a Xyz Monster that mentions it. \
"""
strings = []
