[galaxy-eyes-luminous-dragon]
id = 900004201
alias = 93717133
name = "Galaxy-Eyes Luminous Dragon"
type = "monster effect"
attribute = "light"
race = "dragon"
level = 8
atk = 3000
def = 2500
effect = """\
(This card's name is always treated as "Galaxy-Eyes Photon Dragon".)
You can Special Summon this card (from your hand) by Tributing 2 LIGHT monsters with 2000 or more ATK. \
During the Battle Step, if this card battles an opponent's monster (Quick Effect): \
    You can target that opponent's monster; banish both this card from the field and that target. \
    Return those banished monsters to the field at the end of the Battle Phase, \
    and if you banished an Xyz Monster, its effects are negated. \
"""
strings = ["Banish both this card from the field and that target"]

[galaxy-eyes-full-armor-luminous-dragon]
id = 900004202
set = "photon galaxy-eyes"
name = "Galaxy-Eyes Full Armor Luminous Dragon"
type = "monster xyz effect"
attribute = "light"
race = "dragon"
rank = 8
atk = 3000
def = 2500
effect = """\
2 Level 8 LIGHT monsters
(This card is always treated as a "Photon" card.)
You can also Xyz Summon this card by using a Level 8 "Galaxy-Eyes" Dragon monster you control as material. \
    (Transfer its materials to this card.) \
Cannot be used as material for an Xyz Summon the turn it was Xyz Summoned. \
Xyz Monster your opponent controls loses 500 ATK/DEF for each its material. \
Once per turn (Quick Effect): You can detach 1 material from this card, \
    then target 1 monster your opponent controls; banish it, \
    and if you banished an Xyz Monster, this card gains 1000 ATK for each material it had when it was banished. \
    Return those banished monsters to the field at the End Phase, \
    and if you do, your opponent's monster effects are negated. \
"""
strings = [
    "Xyz Summon by using a Level 8 \"Galaxy-Eyes\" Dragon monster",
    "Detach 1 material to banish 1 monster until the End Phase",
]

[neo-galaxy-eyes-dark-matter-dragon]
id = 900004203
set = "number-c chaos galaxy-eyes"
name = "Number C95: Neo Galaxy-Eyes Dark Matter Dragon"
type = "monster xyz effect"
attribute = "dark"
race = "dragon"
rank = 10
atk = 5000
def = 0
effect = """\
4 Level 10 DARK monsters
You can also Xyz Summon this card by using a "Galaxy-Eyes" Xyz Monster you control as material. \
    (Transfer its materials to this card.) \
Cannot be used as material for an Xyz Summon. \
Once per turn: You can send 1 Dragon monster from your Deck to the GY; \
    attach 1 Dragon Xyz Monster from your Extra Deck or GY to this card as material, \
    then you can banish 1 card your opponent controls or from their GY, face-down. \
If this card has a "Number" DARK Dragon Xyz Monster as material, it gains this effect.
● Cannot be destroyed, or banished, by card effects.
● Once per Battle Phase, at the start of your Battle Phase: \
    You can detach 1 material from this card; this card can make up to 3 attacks on monsters during each Battle Phase this turn.
"""
strings = [
    "Xyz Summon by using \"Galaxy-Eyes\" Xyz Monster",
    "Send 1 Dragon monster to the GY then attach material",
    "Banish 1 card your opponent controls or from their GY, face-down?",
    "Detach 1 material to make up to 3 attacks on monsters",
    "Can make up to 3 attacks on monsters",
    "Banish both the opponent's monster and this card",
]

[photon-stream-eternity]
id = 900004204
set = "photon"
name = "Photon Stream of Eternity"
type = "spell quick-play"
effect = """
If you control a "Galaxy-Eyes" Xyz Monster: banish all Spell/Trap cards your opponent controls, \
    then, if you control "Number 62: Galaxy-Eyes Prime Photon Dragon" or a Xyz Monster that mentions it, \
    negate the effects of all face-up monsters your opponent controls (if any). \
You can only activate this card during your turn, unless you control \
    "Number 62: Galaxy-Eyes Prime Photon Dragon" or a Xyz Monster that mentions it. \
"""
strings = []
