[photonized-galaxy-world]
id = 900003100
name = "Photonized Galaxy World"
set = "photon galaxy"
type = "spell field"
effect = """
You can only activate 1 "{CARD_NAME}" per turn. \
When this card is activated: Place underneath this card, \
    1 "Photon" Continuous Trap from your hand or Deck, \
    and if you do, you can add 1 "Galaxy" Continuous Spell from your Deck or GY to youd hand. \
If you activated a "Photon" or "Galaxy" Continuous Spell/Trap, \
    you can place that card underneath this card when that card resolves. \
This card gains the original effects of all Field Spells and Continuous Spell/Trap(s) underneath it. \
Xyz Summons of your Xyz Monsters cannot be negated. \
"""
strings = [
    "Add 1 \"Galaxy\" Continuous Spell youd hand?",
    "Place the activated card underneath this card?",
]
