[photon-world]
id = 900003100
name = "Photon World"
type = "spell field"
effect = """
You can only activate 1 "{CARD_NAME}" per turn. \
When this card is activated: Place underneath this card, \
    1 "Photon" or "Galaxy" Continuous Spell/Trap from your hand or Deck, \
    and if you do, this effect becomes that card's effect when it is activated. \
"""
strings = []
