EGYPTIAN_GOD_EFFECT = """\
(This card's base Divine Hierarchy is {0}, and is always treated as "{1}".)
Cannot be Special Summoned, except by owner. \
Requires 3 Tributes to Normal Summon (cannot be Normal Set). \
The Normal Summon, effect activations and activated effects of it cannot be negated. \
Your opponent cannot Tribute it, nor use it as material for an Summon. \
Its control cannot switch. \
Its battle position cannot be changed by card effects. \
If card(s) is equipped to it, destroy that card(s). \
Cannot be destroyed by battle with monster with lower Divine Hierarchy, \
    also you take no damage from that battle. \
Unaffected by other cards' effects that would make it leave the field, \
    also other cards' effects are only applied on it for 1 turn, \
    except cards that mentions it and monsters with higher Divine Hierarchy. \
If this card is Special Summoned in Defense Position \
    before resolving a card or effect that targets exactly 1 monster you control, \
    or when an opponent's monster declares an attack, \
    you can make that card, effect, attack now target it. \
During the End Phase, if it was Special Summoned from the GY or Banished, \
    send it to the previous location. \
The above effects cannot be negated nor be copied.\
"""

WICKED_GOD_EFFECT = """\
(This card's base Divine Hierarchy is {0}, and is always treated as "{1}".)
Cannot be Special Summoned. \
Requires 3 Tributes to Normal Summon (cannot be Normal Set). \
The Normal Summon, effect activations, and activated effects of it cannot be negated. \
Your opponent cannot Tribute it, nor use it as material for an Summon. \
Control of it cannot switch. \
Battle position cannot be changed by card effects. \
Cannot be equipped with Equip Cards. \
Cannot be destroyed by battle with monster with lower Divine Hierarchy, \
    also you take no battle damage from that battle. \
Unaffected by other card effects that would make it leave the field, \
    also other card effects are only applied on it for 1 turn, \
    except cards that mentions it and monsters with higher Divine Hierarchy. \
The above effects cannot be negated nor be copied.\
"""

APOSTLE_EFFECT = """\
If this card is Link Summoned: You can add to your hand 1 {0} from your Deck or GY. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
While you control this Link Summoned card, \
    you can Tribute Summon 1 {1} monster in Attack Position during your Main Phase, \
    in addition to your Normal Summon/Set. (You can only gain this effect once per turn.) \
This card can be treated as 3 Tributes for the Tribute Summon of a {1} monster. \
    This effect cannot be negated.\
"""

APOSTLE_GAIN_EFFECT = """\
If you Tribute this card for the Tribute Summon of {0}, it gains this effect.
● After Normal Summoned, you can add 1 Spell/Trap that mentions this card from your Deck or GY to your hand.\
"""