[supreme-presence]
id = 900005000
name = "Supreme Presence of the Overlord"
type = "spell field"
effect = """\
Any Pendulum Monster sent to the GY is sent to Extra Deck face-up instead. \
    This effect cannot be negated. \
Your opponent cannot target this card and cards in your Pendulum Zones with card effects. \
You can destroy 1 other face-up card you control, and if you do, \
    add 1 "Odd-Eyes" card or 1 card that mentions "Supreme King Z-ARC", except the destroyed card, \
    from your Deck or GY to your hand. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
If you Special Summon any of these monsters using a Pendulum Monster(s) as material: You can activate the appropriate effect. \
    You cannot apply that same effect of "{CARD_NAME}" for the rest of this turn.
● Fusion: Special Summon 1 monster from your hand, Deck, or GY with the same original Level as that Fusion Monster, \
    in Defense Position, but it activate its effects this turn.
● Synchro: Add 1 "Fusion" or "Polymerization" Spell from your Deck or GY to your hand.
● Xyz: Take 1 Tuner from your Deck or GY with an equal or lower Level than that Xyz Monster's Rank, \
    and add it to your hand or Special Summon it in Defense Position.
"""
strings = [
    "Destroy 1 face-up card to search",
    "Special Summon a monster with same Level",
    "Add \"Fusion\" Spell",
    "Add or Special Summon a Tuner",
]

[z-arc]
id = 900005001
alias = 13331639
rarity = "gold"
name = "Supreme Overlord Z-Arc"
type = "monster link pendulum effect"
attribute = "dark"
race = "dragon"
scale = 13
link = 4
link-arrow = "top bottom-left bottom bottom-right"
atk = 4000
pendulum-effect = """\
Your other Pendulum Zone's Pendulum Scale become 0. \
    This effect cannot be negated. \
Fusion, Synchro, and Xyz Monsters your opponent controls cannot activate their effects. \
You can Tribute 1 "Supreme King Dragon" monster; Special Summon this card from your Pendulum Zone. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
effect = """\
4 Dragon monsters (1 Fusion, 1 Synchro, 1 Xyz, and 1 Pendulum)
(This card is always treated as "Supreme King Z-ARC".)
Must be Link Summoned, and can then be Pendulum Summoned. \
The Special Summon, effect activations, and activated effects of this card cannot be negated. \
You can Pendulum Summon this card regardless of your Pendulum Scales. \
If this card is Special Summoned: You can destroy all cards your opponent controls, \
    and if you do, inflict damage to your opponent equal to the combined ATK on the field of the destroyed monster(s). \
    This card cannot declare an attack the turn this effect is activated. \
Control of this card cannot switch. This effect cannot be negated. \
Cannot be Tributed, nor be used as material for an Summon. \
Your opponent cannot target or destroy this card with card effects. \
Face-up monsters you control are unaffected by the activated effects of your opponent's Fusion, Synchro and Xyz Monsters. \
If a card(s) is added from the Main Deck to your opponent's hand, except during the Draw Phase: \
    You can destroy that card(s). \
When this card destroys an opponent's monster by battle: \
    You can Special Summon 1 "Supreme King Dragon" monster from your hand, Deck, GY or Extra Deck, \
    ignoring its Summoning conditions, and this is treated as a Special Summoned properly. \
If this card in the Monster Zone is destroyed: \
    You can destroy all cards in your Pendulum Zones (if any), \
    then place this card in your Pendulum Zone. \
"""
strings = [
    "Destroy all cards your opponent controls & inflict damage",
    "Destroy the added card(s)",
    "Special Summon a Dragon",
]

[odd-eyes-venom-dragon]
id = 900005002
set = "odd-eyes supreme-king venom"
name = "Odd-Eyes Venom Dragon Overlord"
type = "monster fusion pendulum effect"
attribute = "dark"
race = "dragon"
level = 10
scale = 11
atk = 3300
def = 2500
pendulum-effect = """\
"""
effect = """\
1 "Odd-Eyes" Dragon Pendulum Monster + 1 "Starving Venom" Fusion Monster
(This card is always treated as an "Supreme King" card.)
Must be Fusion Summoned with above materials on the field, and can then be Pendulum Summoned. \
"""
strings = []

[odd-eyes-wing-dragon]
id = 900005003
set = "odd-eyes supreme-king"
name = "Odd-Eyes Wing Dragon Overlord"
type = "monster synchro pendulum effect"
attribute = "dark"
race = "dragon"
level = 8
scale = 11
atk = 3000
def = 2500
pendulum-effect = """\
"""
effect = """\
1 "Odd-Eyes" Dragon Pendulum Tuner + 1 non-Tuner "Clear Wing" Synchro Monster
(This card is always treated as an "Supreme King" card.)
Must be Synchro Summoned with above materials on the field, and can then be Pendulum Summoned. \
"""
strings = []

[odd-eyes-raging-dragon]
id = 900005004
set = "odd-eyes supreme-king"
name = "Odd-Eyes Raging Dragon Overlord"
type = "monster xyz pendulum effect"
attribute = "dark"
race = "dragon"
level = 7
scale = 11
atk = 3000
def = 2500
pendulum-effect = """\
"""
effect = """\
2 Level 7 monsters (1 "Odd-Eyes" Dragon Pendulum Monster, 1 "Rebellion" Xyz Monster)
(This card is always treated as an "Supreme King" card.)
Must be Xyz Summoned with above materials on the field, and can then be Pendulum Summoned. \
If you can Pendulum Summon Level 7, you can Pendulum Summon this face-up card in your Extra Deck. \
"""
strings = []

[supreme-soul]
id = 900005010
name = "Supreme Soul of the Overlord"
type = "spell link"
link = 3
link-arrow = "top-left top top-right"
effect = """\
This card's activation and effect cannot be negated. \
When this card is activated: \
    Place in your Pendulum Zone 2 "Magician", "Supreme King Gate" Pendulum Monsters with different names \
    from your hand, Deck, GY and/or Extra Deck face-up, and if you do, \
    you can Special Summon 1 "Supreme King Dragon" monster \
    that have Level between (exclusive) the Pendulum Scales of the cards in your Pendulum Zones \
    from your hand, Deck, GY or Extra Deck face-up to your zone this card points to. \
    You can only activate 1 "{CARD_NAME}" per turn. \
Effect activations, and activated effects of monsters this card points cannot be negated. \
You can only use each of the following effects of "{CARD_NAME}" once per turn, and only once that turn.
● (Quick Effect): Place 1 Pendulum Monster from your Monster Zone in your Pendulum Zone.
● (Quick Effect): Special Summon 1 monster from your Pendulum Zone (This is treated as a Pendulum Summon).
● Banish 4 monsters from your hand, field, GY and/or Extra Deck face-up \
    (1 each with "Pendulum Dragon", "Xyz Dragon", "Synchro Dragon", and "Fusion Dragon" in their names); \
    Special Summon 1 "Supreme King Z-ARC" from your Extra Deck, \
    ignoring its Summoning conditions, and this is treated as a Special Summoned properly.
"""
strings = [
    "Special Summon 1 \"Supreme King Dragon\"?",
    "Place monster in Pendulum Zone",
    "Special Summon monster from Pendulum Zone",
    "Summon Z-ARC",
]
