[supreme-presence]
id = 900005000
name = "Supreme Presence of the Overlord"
type = "spell field"
effect = """\
If a Pendulum Monster(s) is sent to your GY, add it to the Extra Deck face-up. \
    This effect cannot be negated. \
Your opponent cannot target this card and cards in your Pendulum Zones with card effects. \
You can destroy 1 other face-up card you control, and if you do, \
    add 1 "Odd-Eyes" card or 1 card that mentions "Supreme King Z-ARC", except the destroyed card, \
    from your Deck or GY to your hand. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
If you Special Summon any of these monsters using a Pendulum Monster(s) as material: You can activate the appropriate effect. \
    You cannot apply that same effect of "{CARD_NAME}" for the rest of this turn.
● Fusion: Special Summon 1 monster from your hand, Deck, or GY with the same original Level as that Fusion Monster, \
    in Defense Position, but it activate its effects this turn.
● Synchro: Add 1 "Fusion" or "Polymerization" Spell from your Deck or GY to your hand.
● Xyz: Take 1 Tuner from your Deck or GY with an equal or lower Level than that Xyz Monster's Rank, \
    and add it to your hand or Special Summon it in Defense Position.
"""
strings = [
    "Destroy 1 face-up card to search",
    "Special Summon a monster with same Level",
    "Add \"Fusion\" Spell",
    "Add or Special Summon a Tuner",
]

[z-arc]
id = 900005001
alias = 13331639
rarity = "gold"
name = "Supreme Overlord Z-Arc"
type = "monster link pendulum effect"
attribute = "dark"
race = "dragon"
scale = 13
link = 4
link-arrow = "top bottom-left bottom bottom-right"
atk = 4000
pendulum-effect = """\
Your other Pendulum Zone's Pendulum Scale become 0. \
    This effect cannot be negated. \
Fusion, Synchro, and Xyz Monsters your opponent controls cannot activate their effects. \
You can Tribute 1 "Supreme King Dragon" monster; Special Summon this card from your Pendulum Zone. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
effect = """\
4 Dragon monsters (1 Fusion, 1 Synchro, 1 Xyz, and 1 Pendulum)
(This card is always treated as "Supreme King Z-ARC".)
Must be Link Summoned, and can then be Pendulum Summoned. \
The Special Summon, effect activations, and activated effects of this card cannot be negated. \
You can Pendulum Summon this card regardless of your Pendulum Scales. \
If this card is Special Summoned: You can destroy all cards your opponent controls, \
    and if you do, inflict damage to your opponent equal to the combined ATK on the field of the destroyed monster(s). \
    This card cannot declare an attack the turn this effect is activated. \
Control of this card cannot switch. This effect cannot be negated. \
Cannot be Tributed, nor be used as material for an Summon. \
Your opponent cannot target or destroy this card with card effects. \
Face-up monsters you control are unaffected by the activated effects of your opponent's Fusion, Synchro and Xyz Monsters. \
If a card(s) is added from the Main Deck to your opponent's hand, except during the Draw Phase: \
    You can destroy that card(s). \
When this card destroys an opponent's monster by battle: \
    You can Special Summon 1 "Supreme King Dragon" monster from your hand, Deck, GY or Extra Deck, \
    ignoring its Summoning conditions, and this is treated as a Special Summoned properly. \
If this card in the Monster Zone is destroyed: \
    You can destroy all cards in your Pendulum Zones (if any), \
    then place this card in your Pendulum Zone. \
"""
strings = [
    "Destroy all cards your opponent controls & inflict damage",
    "Destroy the added card(s)",
    "Special Summon a Dragon",
]

[odd-eyes-venom-dragon]
id = 900005002
set = "odd-eyes venom supreme-king"
name = "Odd-Eyes Venom Dragon Overlord"
type = "monster fusion pendulum effect"
attribute = "dark"
race = "dragon"
level = 10
scale = 11
atk = 3000
def = 2500
pendulum-effect = """\
Once per turn, during the Standby Phase: Place 1 Venemy Counter on each face-up monster your opponent controls. \
All monsters on the field, except DARK Dragon monsters, lose 200 ATK for each Venemy Counter on the field. \
Once per turn, if a monster you control battles an opponent's monster, before damage calculation: \
    You can make that monster you control gains 500 ATK for each Venemy Counter on the field until the end of the Damage Step. \
"""
effect = """\
1 "Odd-Eyes" Dragon Pendulum Monster + 1 "Starving Venom" Fusion Monster
(This card is always treated as an "Supreme King" card.)
Must be Fusion Summoned with above materials on the field, and can then be Pendulum Summoned. \
If this card is Fusion Summoned: \
    You can make this card gain ATK equal to the combined ATK of all monsters your opponent currently controls, \
    until the end of this turn. \
Each time a card(s) is sent from the field to the GY, place 1 Venemy Counter on this card for each sent card. \
All monsters on the field, except DARK Dragon monsters, lose 200 ATK for each Venemy Counter on the field. \
Once per turn (Qick Effect): You can target 1 face-up monster your opponent controls or in their GY; \
    until the end of this turn, negate the effects of that monster, \
    also this card gains its original ATK and effects. \
If this card in the Monster Zone is destroyed by battle or card effect: \
    You can place this card in your Pendulum Zone. \
"""
strings = [
    "Place Venemy Counter",
    "Make 1 monster gain ATK up by Venemy Counter",
    "Negate effect & gain effect, ATK of a monster",
]

[odd-eyes-wing-dragon]
id = 900005003
set = "odd-eyes supreme-king"
name = "Odd-Eyes Wing Dragon Overlord"
type = "monster synchro pendulum effect"
attribute = "dark"
race = "dragon"
level = 8
scale = 11
atk = 3000
def = 2500
pendulum-effect = """\
Once per turn, if your monster battles an opponent's monster, before damage calculation: \
    You can make that monster you control gain ATK equal to the current ATK of the opponent's monster it is battling until the end of the Damage Step. \
"""
effect = """\
1 "Odd-Eyes" Dragon Pendulum Tuner + 1 non-Tuner "Clear Wing" Synchro Monster
(This card is always treated as an "Supreme King" card.)
Must be Synchro Summoned with above materials on the field, and can then be Pendulum Summoned. \
If this card is Synchro Summoned: \
    You can destroy all monsters your opponent currently controls, \
    and if you do, this card gains 500 ATK for each, until the end of this turn. \
Once per turn, at the start of the Damage Step, if this card battles an opponent's monster: \
    You can destroy that opponent's monster, and if you do, \
    this card gains ATK equal to the destroyed monster's original ATK until the end of this turn, \
    also, this card can make a second attack in a row. \
Once per turn (Quick Effect): You can target 1 face-up monster your opponent controls; \
    until the end of this turn, negate the effects of that monster, also change its ATK to 0. \
If this card in the Monster Zone is destroyed by battle or card effect: \
    You can place this card in your Pendulum Zone. \
"""
strings = [
    "Gain ATK of battling monster's ATK",
    "Destroy battling monster",
    "Negate effect & down attack of a monster",
]

[odd-eyes-raging-dragon]
id = 900005004
set = "odd-eyes supreme-king"
name = "Odd-Eyes Raging Dragon Overlord"
type = "monster xyz pendulum effect"
attribute = "dark"
race = "dragon"
level = 7
scale = 11
atk = 3000
def = 2500
pendulum-effect = """\
Once per turn, if your monster battles an opponent's monster, before damage calculation: \
    You can halve the ATK of the opponent's monster it is battling until the end of the Damage Step. \
"""
effect = """\
2 Level 7 monsters (1 "Odd-Eyes" Dragon Pendulum Monster, 1 "Rebellion" Xyz Monster)
(This card is always treated as an "Supreme King" card.)
Must be Xyz Summoned with above materials on the field, and can then be Pendulum Summoned. \
If you can Pendulum Summon Level 7, you can Pendulum Summon this face-up card in your Extra Deck. \
If this card is Xyz Summoned, it can make up to 3 attacks. \
Once per turn: You can detach 1 material from this card; \
    destroy as many cards your opponent controls as possible, \
    and if you do, this card gains 200 ATK for each, until the end of this turn. \
Once per turn (Quick Effect): You can target 1 face-up monster your opponent controls; \
    until the end of this turn, negate the effects of that monster, also its ATK becomes half its current ATK, \
    and if it does, this card gains that lost ATK. \
If this card in the Monster Zone is destroyed by battle or card effect: \
    You can place this card in your Pendulum Zone. \
"""
strings = [
    "Halve ATK of battling monster",
    "Can make 3 attacks",
    "Destroy card on the field",
    "Negate effect & halve ATK of a monster",
]

[supreme-king-dragon-venowurm]
id = 900005005
set = "supreme-king-dragon"
name = "Supreme King Dragon Venowurm"
type = "monster pendulum effect"
attribute = "dark"
race = "dragon"
level = 4
scale = 8
atk = 1500
def = 1000
pendulum-effect = """\
Once per turn: You can Fusion Summon 1 Dragon Fusion Monster from your Extra Deck, \
    using monsters from your hand or field as Fusion Materials. \
"""
effect = """\
Cannot be used as Fusion Material, except for the Fusion Summon of a Dragon Fusion Monster or Pendulum Fusion Monster. \
If this card is in your hand, GY or Extra Deck: \
    You can target 1 Pendulum Monster or Dragon monster with 2500 ATK more you control; \
    its ATK become 0 and negate its effects, \
    and if you do, Special Summon this card in Defense Position, then the targeted monster's Attribute become DARK. \
    You can only use this effect of "Supreme King Dragon Venowurm" once per turn. \
Once per turn, you can Fusion Summon 1 Fusion Monster from your Extra Deck, \
    using this card you control as Fusion Material, as well as other monsters you control or cards in your Pendulum Zones. \
"""
strings = []

[supreme-king-dragon-wingwurm]
id = 900005006
set = "supreme-king-dragon"
name = "Supreme King Dragon Wingwurm"
type = "monster pendulum tuner effect"
attribute = "dark"
race = "dragon"
level = 4
scale = 8
atk = 1500
def = 1000
pendulum-effect = """\
Once per turn: You can target 1 Pendulum Monster you control; this turn, \
    that face-up monster is treated as a Tuner, also its Level becomes 1 (even if this card leaves the field). \
"""
effect = """\
Cannot be used as Synchro Material, except for the Synchro Summon of a Dragon Synchro Monster or Pendulum Synchro Monster. \
If this card is in your hand, GY or Extra Deck: \
    You can target 1 Pendulum Monster or Dragon monster with 2500 ATK more you control; \
    its ATK become 0 and negate its effects, \
    and if you do, Special Summon this card in Defense Position, then reduce targeted monster's Level by this card' Level (min. 1). \
    You can only use this effect of "Supreme King Dragon Wingwurm" once per turn. \
Once per turn: You can Special Summon 1 card from your Pendulum Zone; but it has its effects negated (if any), \
    and if you do, immediately after this effect resolves, Synchro Summon 1 Synchro Monster using only that monster and this card. \
"""
strings = ["Make monster become Tuner"]

[supreme-king-dragon-rebelliwurm]
id = 900005007
set = "supreme-king-dragon"
name = "Supreme King Dragon Rebelliwurm"
type = "monster pendulum effect"
attribute = "dark"
race = "dragon"
level = 4
scale = 8
atk = 1500
def = 1000
pendulum-effect = """\
Once per turn: You can target 1 face-up Xyz Monster you control, and 1 Pendulum Monster that has Level you control; until the end of this turn, \
    that Xyz Monster's Rank becomes equal to the Level of the other, \
    also you can use it as an Xyz Material for an Xyz Summon using its Rank as if it were a Level. \
    (even if this card leaves the field). \
"""
effect = """\
Cannot be used as Xyz Material, except for the Xyz Summon of a Dragon Xyz Monster or Pendulum Xyz Monster. \
If this card is in your hand, GY or Extra Deck: \
    You can target 1 Pendulum Monster or Dragon monster with 2500 ATK more you control; \
    its ATK become 0 and negate its effects, \
    and if you do, Special Summon this card in Defense Position, then the targeted monster's Level becomes the same as this card's. \
    You can only use this effect of "Supreme King Dragon Rebelliwurm" once per turn. \
Once per turn: You can Special Summon 1 card from your Pendulum Zone; but it has its effects negated (if any), \
    and if you do, immediately after this effect resolves, Xyz Summon 1 Xyz Monster using only that monster and this card. \
"""
strings = ["Make Xyz monster gain Level"]

[supreme-soul]
id = 900005010
name = "Supreme Soul of the Overlord"
type = "spell link"
link = 3
link-arrow = "top-left top top-right"
effect = """\
This card's activation and effect cannot be negated. \
When this card is activated: \
    Place in your Pendulum Zone 2 "Magician", "Supreme King Gate" Pendulum Monsters with different names \
    from your hand, Deck, GY and/or Extra Deck face-up, and if you do, \
    you can Special Summon 1 "Supreme King Dragon" monster \
    that have Level between (exclusive) the Pendulum Scales of the cards in your Pendulum Zones \
    from your hand, Deck, GY or Extra Deck face-up to your zone this card points to. \
    You can only activate 1 "{CARD_NAME}" per turn. \
Effect activations, and activated effects of monsters this card points cannot be negated. \
You can only use each of the following effects of "{CARD_NAME}" once per turn, and only once that turn.
● (Quick Effect): Place 1 Pendulum Monster from your Monster Zone in your Pendulum Zone.
● (Quick Effect): Special Summon 1 monster from your Pendulum Zone (This is treated as a Pendulum Summon).
● Banish 4 monsters from your hand, field, GY and/or Extra Deck face-up \
    (1 each with "Pendulum Dragon", "Xyz Dragon", "Synchro Dragon", and "Fusion Dragon" in their names); \
    Special Summon 1 "Supreme King Z-ARC" from your Extra Deck, \
    ignoring its Summoning conditions, and this is treated as a Special Summoned properly.
"""
strings = [
    "Special Summon 1 \"Supreme King Dragon\"?",
    "Place monster in Pendulum Zone",
    "Special Summon monster from Pendulum Zone",
    "Summon Z-ARC",
]
