set_name = "triplesix"
setcodes = ["./setcode.toml"]
pic_field_path = "D:/Games/EdoPro/pics/field"

packs = [
    "./pack/_update",
    "./pack/egyptian-god",
    "./pack/sacred-beast",
    "./pack/palladium",
    "./pack/blue-eyes",
    "./pack/red-eyes",
    "./pack/elemental-neos",
    "./pack/cosmic-dragon",
    "./pack/galaxy-eyes",
    "./pack/z-arc",
    "./pack/cyberse",
]

skip_compile_packs = [
    "./pack/_update",
    "./pack/egyptian-god",
    "./pack/sacred-beast",
    "./pack/palladium",
    "./pack/blue-eyes",
    "./pack/red-eyes",
    "./pack/elemental-neos",
    "./pack/cosmic-dragon",
    # "./pack/galaxy-eyes",
    "./pack/z-arc",
    "./pack/cyberse",
]
