set_name = "triplesix"
pic_field_path = "D:/Games/EdoPro/pics/field"
setcodes = ["./setcode.toml"]

packs = [
    "./pack/divine-god",
    "./pack/palladium",
    "./pack/blue-eyes",
    "./pack/duel-dragon",
]

skip_compile_packs = [
    "./pack/divine-god",
    # "./pack/palladium",
    "./pack/blue-eyes",
    "./pack/duel-dragon",
]
