set_name = "triplesix"
setcodes = ["./setcode.toml"]
pic_field_path = "D:/Games/EdoPro/pics/field"

packs = [
    "./pack/divine-god",
    "./pack/palladium",
    "./pack/blue-eyes",
    "./pack/duel-dragon",
    "./pack/z-arc",
]

skip_compile_packs = [
    "./pack/divine-god",
    "./pack/palladium",
    "./pack/blue-eyes",
    # "./pack/duel-dragon",
    "./pack/z-arc",
]
