set_name = "triplesix"
setcodes = ["./setcode.toml"]
pic_field_path = "D:/Games/EdoPro/pics/field"

packs = [
    "./pack/_update",
    "./pack/divine-god",
    "./pack/palladium",
    "./pack/blue-eyes",
    "./pack/neo-spacian-hero",
    "./pack/cosmic-dragon",
    "./pack/z-arc",
]

skip_compile_packs = [
    "./pack/_update",
    "./pack/divine-god",
    "./pack/palladium",
    "./pack/blue-eyes",
    # "./pack/neo-spacian-hero",
    "./pack/cosmic-dragon",
    "./pack/z-arc",    
]
