set_name = "triplesix"
setcodes = ["./setcode.toml"]
# pic_field_path = "D:/Games/EdoPro/pics/field"
pic_field_path = "C:/ProjectIgnis/pics/field"

packs = [
    "./pack/_update",
    "./pack/egyptian-god",
    "./pack/sacred-beast",
    "./pack/palladium",
    "./pack/blue-eyes",
    "./pack/red-eyes",
    "./pack/elemental-neos",
    "./pack/evil-hero",
    "./pack/cosmic-dragon",
    "./pack/numeron",
    "./pack/galaxy-eyes",
    "./pack/barian",
    "./pack/z-arc",
    "./pack/code-talker",
]

skip_compile_packs = [
    "./pack/_update",
    "./pack/egyptian-god",
    "./pack/palladium",
    "./pack/blue-eyes",
    "./pack/red-eyes",
    "./pack/sacred-beast",
    "./pack/elemental-neos",
    "./pack/evil-hero",
    "./pack/cosmic-dragon",
    # "./pack/numeron",
    # "./pack/galaxy-eyes",
    # "./pack/barian",
    "./pack/z-arc",
    "./pack/code-talker",
]
