aesir = 0x4b
archfiend = 0x45
black-luster-soldier = 0x10cf
blue-eyes = 0xdd
chaos = 0xcf
clear-wing = 0xff
cxyz = 0x1073
dododo = 0x82
elemental-hero = 0x3008
evil-hero = 0x6008
exodia = 0xde
forbidden-one = 0x40
fusion = 0x46
fusion-dragon = 0x1046
gagaga = 0x54
gaia-the-fierce-knight = 0xbd
galaxy = 0x7b
galaxy-eyes = 0x107b
gogogo = 0x59
guardian = 0x52
hero = 0x8
infernity = 0xb
junk = 0x43
kuriboh = 0xa4
magician = 0x98
majestic = 0x3f
neo-spacian = 0x1f
neos = 0x9
nordic = 0x42
nordic-alfar = 0xa042
nordic-ascendant = 0x3042
nordic-beast = 0x6042
nordic-relic = 0x5042
number = 0x48
number-c = 0x1048
number-c39 = 0x5048
numeron = 0x14b
odd-eyes = 0x99
onomat = 0x139
palladium = 0x13a
pendulum = 0xf2
pendulum-dragon = 0x10f2
phantasm = 0x145
phantom-beast = 0x1b
photon = 0x55
predaplant = 0x10f3
prophecy = 0x6e
rank-down-magic = 0x15d
rank-up-magic = 0x95
rebellion = 0x13b
red-dragon-archfiend = 0x1045
red-eyes = 0x3b
rose-dragon = 0x1123
stardust = 0xa3
starving-venom = 0x1050
supreme-king = 0xf8
supreme-king-dragon = 0x20f8
supreme-king-gate = 0x10f8
synchro = 0x17 
synchro-dragon = 0x2017
synchron = 0x1017
utopia = 0x107f
utopic = 0x7f
venom = 0x50
void = 0xc5
warrior = 0x66
xyz = 0x73
xyz-dragon = 0x2073
zexal = 0x7e
zs = 0x207e
zubaba = 0x8f
zw = 0x107e