[mirror-force-launcher]
id = 29649320
generate-pic = false
card-limit = "ocg tcg"
name = "Mirror Force Launcher"
type = "trap continuous"
effect = """\
Once per turn, during your Main Phase: \
    You can discard 1 monster; add 1 "Mirror Force" from your Deck or GY to your hand. \
If this Set card is destroyed by your opponent's card effect and sent to your GY: \
    You can Set this card from your GY and 1 "Mirror Force" from your hand, Deck, or GY. They can be activated this turn. \
"""
strings = ["Add \"Mirror Force\""]

[elemental-hero-glow-neos]
id = 85507811
generate-pic = false
generate-script = false
card-limit = "ocg tcg"
name = "Elemental HERO Glow Neos"
set = "elemental-hero neos"
type = "monster fusion effect"
attribute = "light"
race = "warrior"
level = 7
atk = 2500
def = 2000
effect = """\
"Elemental HERO Neos" + "Neo-Spacian Glow Moss"
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. \
    (You do not use "Polymerization".) \
During the End Phase: Shuffle this card into the Extra Deck. \
Once per turn, during your Main Phase 1: You can target 1 face-up card your opponent controls; \
    destroy that target, then apply the effect based on its type.
● Monster: This card cannot attack this turn.
● Spell: This card can attack your opponent directly this turn.
● Trap: Change this card to Defense Position.
"""
strings = ["", "Destroy that target, then apply the effect based on its type"]

[elemental-hero-dark-neos]
id = 28677304
generate-pic = false
generate-script = false
card-limit = "ocg tcg"
name = "Elemental HERO Dark Neos"
set = "elemental-hero neos"
type = "monster fusion effect"
attribute = "dark"
race = "warrior"
level = 7
atk = 2500
def = 2000
effect = """\
"Elemental HERO Neos" + "Neo-Spacian Dark Panther"
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. \
    (You do not use "Polymerization".) \
If this card is not already targeting a monster with its effect: \
    You can target 1 face-up Effect Monster on the field; \
    while you control this face-up card, that target's effect on the field is negated. \
During the End Phase: Shuffle this card into the Extra Deck. \
"""
strings = ["", "Negate the effect of 1 face-up card on the field"]

[elemental-hero-aqua-neos]
id = 55171412
generate-pic = false
generate-script = false
card-limit = "ocg tcg"
name = "Elemental HERO Aqua Neos"
set = "elemental-hero neos"
type = "monster fusion effect"
attribute = "water"
race = "warrior"
level = 7
atk = 2500
def = 2000
effect = """\
"Elemental HERO Neos" + "Neo-Spacian Aqua Dolphin"
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. \
    (You do not use "Polymerization".) \
Once per turn: You can discard 1 card; \
    destroy 1 random card in your opponent's hand. \
During the End Phase: Shuffle this card into the Extra Deck. \
"""
strings = [
    "",
    "Discard 1 card to destroy 1 random card in your opponent's hand",
]

[elemental-hero-grand-neos]
id = 48996569
generate-pic = false
generate-script = false
card-limit = "ocg tcg"
name = "Elemental HERO Grand Neos"
set = "elemental-hero neos"
type = "monster fusion effect"
attribute = "earth"
race = "warrior"
level = 7
atk = 2500
def = 2000
effect = """\
"Elemental HERO Neos" + "Neo-Spacian Grand Mole"
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. \
    (You do not use "Polymerization".) \
Once per turn: You can target 1 monster your opponent controls; \
    return that target to the hand. \
During the End Phase: Shuffle this card into the Extra Deck.
"""
strings = ["", "Return 1 monster your opponent controls to the hand"]

[opening-of-the-spirit-gates]
id = 80312545
generate-pic = false
generate-script = false
card-limit = "ocg tcg"
name = "Opening of the Spirit Gates"
type = "spell continuous"
effect = """
When this card is activated: Add 1 "Uria, Lord of Searing Flames", "Hamon, Lord of Striking Thunder", \
    or "Raviel, Lord of Phantasms", OR 1 monster that specifically lists any of those cards in its text, \
    from your Deck to your hand. \
Once per turn: You can discard 1 card; \
    Special Summon 1 Fiend monster with 0 ATK/DEF from your GY. \
Once per turn, if you control a Level 10 monster: \
    You can add 1 Continuous Spell from your GY to your hand. \
You can only activate 1 "Opening of the Spirit Gates" per turn. \
"""
strings = [
    "Search card mentions Sacred Beast",
    "Special Summon a Fiend monster with 0 ATK/DEF",
    "Add Continuous Spell from GY to hand",
]

[awakening-of-the-sacred-beasts]
id = 53701259
generate-pic = false
generate-script = false
card-limit = "ocg tcg"
name = "Awakening of the Sacred Beasts"
type = "trap continuous"
effect = """
This card gains these effects based on the number of \
    "Uria, Lord of Searing Flames", "Hamon, Lord of Striking Thunder", and/or "Raviel, Lord of Phantasms" \
    with different names you control.
● 1+: Each time your opponent Normal or Special Summons a monster(s): \
    Gain LP equal to the ATK of that monster(s).
● 2+: Negate the activated effects of monsters your opponent controls.
● 3: Any monsters sent to your opponent's GY are banished instead.
Once per your turn, if you control a Level 10 monster: \
    You can add 1 Continuous Trap from your GY to your hand. \
"""
strings = ["Add Continuous Trap from GY to hand"]

[hyper-blaze]
id = 16317140
generate-pic = false
generate-script = false
card-limit = "ocg tcg"
name = "Hyper Blaze"
type = "trap continuous"
effect = """
To Special Summon "Uria, Lord of Searing Flames" using its own procedure, \
    you can also use face-down Traps you control. \
Once per battle, when an attack is declared involving your "Uria, Lord of Searing Flames": \
    You can send 1 Trap from your hand or Deck to the GY; \
    its ATK/DEF become the number of face-up Traps on the field and in the GYs x 1000, \
    for the rest of this turn. \
Once per turn: You can discard 1 card; \
    add to your hand or Special Summon, \
    1 "Uria, Lord of Searing Flames", "Hamon, Lord of Striking Thunder", or "Raviel, Lord of Phantasms" \
    from your GY, ignoring its Summoning conditions. \
"""
strings = [
    "Send Trap to gain ATK",
    "Return or Special Summon 1 Sacred Beast",
    "Select a Sacred Beast",
    "Special Summon it",
]

[unending-nightmare]
id = 69452756
generate-pic = false
generate-script = false
card-limit = "ocg tcg"
name = "Unending Nightmare"
type = "trap continuous"
effect = """
You can pay 1000 LP, then target 1 face-up Spell/Trap on the field; destroy it. \
You can only activate this effect of "Unending Nightmare" once per Chain. \
"""
strings = ["Pay 1000 LP, destroy 1 face-up Spell/Trap"]

[duamutef-blessing-horus]
id = 11335209
generate-pic = false
generate-script = false
card-limit = "ocg tcg"
name = "Duamutef, Blessing of Horus"
set = "horus"
type = "monster effect"
attribute = "water"
race = "beast"
level = 8
atk = 0
def = 0
effect = """
If you control "King's Sarcophagus", you can Special Summon this card (from your GY). \
    You can only Special Summon "Duamutef, Blessing of Horus" once per turn this way. \
Gains 1200 ATK/DEF for each "Horus" monster you control. \
If another card(s) you control leaves the field by an opponent's card effect, \
    while this card is in your Monster Zone (except during the Damage Step): \
    You can draw cards equal to the number of monsters with different names in your Main Monster Zone. \
    You can only use this effect of "Duamutef, Blessing of Horus" once per turn. \
"""
strings = ["Special Summon itself", "Draw cards equal to monsters you control"]

[blue-eyes-alternative-white-dragon]
id = 38517738
alias = 38517737
generate-script = false
card-limit = "ocg tcg"
name = "Blue-Eyes Alternative White Dragon"
type = "monster effect nomi"
attribute = "light"
race = "dragon"
level = 8
atk = 3000
def = 2500
effect = """
Cannot be Normal Summoned/Set. \
Must first be Special Summoned (from your hand) by revealing "Blue-Eyes White Dragon" in your hand. \
    You can only Special Summon "Blue-Eyes Alternative White Dragon" once per turn this way. \
This card's name becomes "Blue-Eyes White Dragon" while it is on the field or in the Graveyard. \
Once per turn: You can target 1 monster your opponent controls; destroy it. \
    This card cannot attack the turn this effect is activated. \
"""
strings = ["Destroy 1 monster your opponent controls"]
