[mirror-force-launcher]
generate-pic = false
card-limit = "ocg tcg"
id = 29649320
name = "Mirror Force Launcher"
type = "trap continuous"
effect = """\
Once per turn, during your Main Phase: \
    You can discard 1 monster; add 1 "Mirror Force" from your Deck or GY to your hand. \
If this Set card is destroyed by your opponent's card effect and sent to your GY: \
    You can Set this card from your GY and 1 "Mirror Force" from your hand, Deck, or GY. They can be activated this turn. \
"""
strings = ["Add \"Mirror Force\""]
