[card.dark-rebellion-magician]
id = 950000015
set = "rebellion xyz-dragon magician"
name = "Dark Rebellion Magician"
type = "monster xyz pendulum effect"
attribute = "dark"
race = "spellcaster"
rank = 4
pendulum-scale = 8
atk = 2500
def = 2000
pendulum-effect = """\
Once per turn, you can target 1 Dragon Xyz Monster you control; \
    Special Summon from your Extra Deck, 1 Xyz Monster that is 1 Rank higher than that monster you control, \
    by using it as material, and if you do, attach this card to it as additional material. \
    (This is treated as an Xyz Summon. Transfer its materials to the Summoned monster.) \
"""
effect = """\
2 Level 4 Pendulum Monsters
(This card is always treated as a "Xyz Dragon" card.)
If you can Pendulum Summon Level 4, you can Pendulum Summon this face-up card in your Extra Deck. \
If an DARK Xyz Monster you control would activate an effect by detaching an material(s), \
    you can detach materials from this card instead of those materials. \
    This effect cannot be negated. \
If "Rebellion" Dragon monster's ATK is changed: \
    You can inflict damage to your opponent equal to the changed amount. \
    You can only use this effects of "Dark Rebellion Magician" once per turn. \
${TO_PZONE_WHEN_DESTROYED} \
"""
strings = [
    "Rank-Up Dragon Xyz Monster",
    "Inflict damage equal to \"Rebellion\" ATK change",
]

[card.sorcerer-sky-iris]
id = 950000016
name = "Sorcerer of Sky Iris"
type = "monster fusion pendulum effect"
attribute = "wind"
race = "spellcaster"
level = 8
pendulum-scale = 8
atk = 2800
def = 2600
pendulum-effect = """\
All monsters you control gain 100 ATK and DEF for each face-up Pendulum Monster with different names in your Extra Deck. \
If a Pendulum Monster(s) you control is destroyed by battle or by card effect: \
    You can Special Summon this card from your Pendulum Zone in Defense Position, \
    then, you can place 1 of those monsters in your Pendulum Zone. \
    You can only use this effect of "Sorcerer of Sky Iris" once per turn. \
"""
effect = """\
1 "Magician" Pendulum Monster + 1 monster that was Special Summoned from Extra Deck
If this card is Fusion Summoned: You can add 1 Pendulum Monster form your Deck or Extra Deck face-up to your hand. \
You can Special Summon 1 monster from your Pendulum Zone, ignoring their Summoning conditions, \
    and if you do, you can place this card in your Pendulum Zone. \
During the End Phase: \
    You can Special Summon as many monsters as possible from your GY or Extra Deck face-up \
    that were destroyed by battle or an opponent's card effect this turn. \
You can only use each effect of "Sorcerer of Sky Iris" once per turn. \
"""
strings = [
    "Place 1 of destroyed monsters in Pendulum Zone",
    "Special Summon monster from Pendulum Zone",
    "Special Summon all the destroyed monster",
]

[supreme-soul]
id = 900005018
name = "Supreme Soul of the Overlord"
type = "spell link"
link = 3
link-arrow = "top-left top top-right"
effect = """\
This card's activation and effect cannot be negated. \
When this card is activated: \
    Place in your Pendulum Zone 2 "Magician", "Supreme King Gate" Pendulum Monsters with different names \
    from your hand, Deck, GY and/or Extra Deck face-up, and if you do, \
    you can Special Summon 1 "Supreme King Dragon" monster \
    that have Level between (exclusive) the Pendulum Scales of the cards in your Pendulum Zones \
    from your hand, Deck, GY or Extra Deck face-up to your zone this card points to. \
    You can only activate 1 "{CARD_NAME}" per turn. \
Effect activations, and activated effects of monsters this card points cannot be negated. \
You can only use each of the following effects of "{CARD_NAME}" once per turn, and only once that turn.
● (Quick Effect): Place 1 Pendulum Monster from your Monster Zone in your Pendulum Zone.
● (Quick Effect): Special Summon 1 monster from your Pendulum Zone (This is treated as a Pendulum Summon).
● You can target 1 "Supreme King Z-ARC" you control; it can attack all opponent's monsters once each this turn.
● Banish 4 monsters from your hand, field, GY and/or Extra Deck face-up \
    (1 each with "Pendulum Dragon", "Xyz Dragon", "Synchro Dragon", and "Fusion Dragon" in their names); \
    Special Summon 1 "Supreme King Z-ARC" from your Extra Deck, \
    ignoring its Summoning conditions, and this is treated as a Special Summoned properly.
"""
strings = [
    "Special Summon 1 \"Supreme King Dragon\"?",
    "Place monster in Pendulum Zone",
    "Special Summon monster from Pendulum Zone",
    "Z-ARC can attack all opponent's monsters",
    "Summon Z-ARC",
]
