[messiah-elysium]
id = 900007000
name = "Messiah's Elysium"
type = "spell field"
effect = """
You can only activate 1 "{CARD_NAME}" per turn. \
When this card is activated: \
    you can place 1 Field Spell from your hand, Deck or GY underneath this card, \
    except "{CARD_NAME}". \
While you control a Link Pendulum Monster Card, \
    your opponent cannot target this card with card effects, \
    also it is unaffected by other card effects. \
    This effects cannot be negated. \
If you activated a Continuous Spell/Trap, \
    you can place that card underneath this card when that card resolves. \
This card gains the original effects of all Field Spells and Continuous Spell/Trap(s) underneath it. \
Thrice per turn: You can target 1 face-up monster you control; \
    move that monster you control to another of your Main Monster Zones. \
"""
strings = [
    "Pay the cost?",
    "Place a Continuous Spell/Trap underneath this card?",
    "Move monster to another of your Main Monster Zones",
]

[messiah-deity]
id = 900007001
rarity = "gold"
name = "Messiah, Supreme Deity of Dragons"
type = "monster link pendulum effect"
attribute = "divine"
race = "creator-god"
link = 7
link-arrow = "top-left top-right left right bottom-left bottom bottom-right"
scale = 13
atk = 4000
pendulum-effect = """\
Cannot be targeted by card effects, also unaffected by other card effects. \
    The above effects cannot be negated. \
The Pendulum Scale of card in your other Pendulum Zone become 0. \
During either player's turn, except the turn this card was placed Pendulum Zones (Quick Effect): \
    You can shuffle this card into the Extra Deck, and if you do, it becomes the Standby Phase of your next turn. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
effect = """\
Cannot be Link Summoned. \
Must be Special Summoned (from your Extra Deck face-down or Pendulum Zones) by Tributing 3 Link Pendulum Monsters. \
    You can only Special Summon "{CARD_NAME}" once per turn this way, \
    except the turn this card was placed Pendulum Zones. \
This card's Special Summon cannot be negated. \
You can only control 1 "{CARD_NAME}". \
When Special Summoned, other cards and effects cannot be activated, \
    also after that, you can attach 1 monster from Extra Deck to this card. \
Cannot be Tributed, or use as material for an Summon. \
Control of it cannot switch. \
Cannot be destroyed by card effects. \
Unaffected by other card effects, except "Messiah's Elysium". \
The above effects cannot be negated or be copied. \
Once per turn: You can attach any number of other monsters you control to this card. \
This card's gains the original effects of all monsters attached to it, except "{CARD_NAME}". \
(Quick Effect): You can destroy 2 Link Pendulum Monster Cards in your Pendulum Zones, and if you do, \
    add all other Pendulum Monsters that attached to this card, or in your GY to the Extra Deck face-up (if any), \
    also, place this card from your Monster Zone, Extra Deck face-up, or GY in your Pendulum Zone, \
    then, you can place 1 Pendulum Monster from your Deck in your Pendulum Zone. \
    This effect's activation and effect cannot be negated. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = [
    "Attach 1 monster from Extra Deck to this card?",
    "Shuffle this card into the Extra Deck & move to the Standby Phase of your next turn",
    "Attach any number of other monsters you control",
    "Place this card in your Pendulum Zone",
    "Place 1 Pendulum Monster from your Deck in your Pendulum Zone?",
]

[messiah-origin]
id = 900007002
name = "Origin Messiah of Dragons"
type = "monster link pendulum effect"
attribute = "divine"
race = "divine-beast"
link = 2
link-arrow = "left bottom-right"
scale = 0
atk = 0
pendulum-effect = """\
{MESSIAH_BABY_PENDULUM_EFFECT} \
"""
effect = """\
2 non-Link monsters
{MESSIAH_BABY_MONSTER_EFFECT|Dragon monster|hand or Deck}\
Once per turn, during the End Phase: Destroy this card. \
"""
strings = [
    "Add to Extra Deck",
    "Place in Pendulum Zone",
    "Special Summon 1 Dragon monster from hand or Deck",
    "Destroy itself",
]

[messiah-genesis]
id = 900007003
name = "Genesis Messiah of Dragons"
type = "monster link pendulum effect"
attribute = "divine"
race = "divine-beast"
link = 2
link-arrow = "right bottom-left"
scale = 13
atk = 0
pendulum-effect = """\
{MESSIAH_BABY_PENDULUM_EFFECT} \
"""
effect = """\
2 non-Link monsters
{MESSIAH_BABY_MONSTER_EFFECT|Dragon monster|hand or Deck}\
Once per turn, during the End Phase: Destroy this card. \
"""
strings = [
    "Add to Extra Deck",
    "Place in Pendulum Zone",
    "Special Summon 1 Dragon monster from hand or Deck",
    "Destroy itself",
]

[messiah-newborn]
id = 900007004
name = "Newborn Messiah of Dragons"
type = "monster link pendulum effect"
attribute = "divine"
race = "divine-beast"
link = 3
link-arrow = "top-left top-right bottom"
scale = 5
atk = 0
pendulum-effect = """\
{MESSIAH_BABY_PENDULUM_EFFECT} \
"""
effect = """\
3 non-Link monsters
Cannot be destroyed by battle. \
You take no battle damage from battles involving this card. \
{MESSIAH_BABY_MONSTER_EFFECT|monster|GY or banishment}\
"""
strings = [
    "Add to Extra Deck",
    "Place in Pendulum Zone",
    "Special Summon a monster from GY or banishment",
]
