MESSIAH_BABY_PENDULUM_EFFECT = """\
Pendulum Summons of your monsters cannot be negated. \
If you Pendulum Summon a monster(s): Add this card to your Extra Deck face-up.\
"""

MESSIAH_BABY_MONSTER_EFFECT = """\
During the Main Phase, you can activate 1 of these effects, \
    but you cannot apply that same effect of "{CARD_NAME}" again this turn. \
    If you control a card whose original name is "Messiah's Elysium", \
    you can apply the above effects without cost.
● While this card is in your Extra Deck face-up: \
    You can shuffle 1 monster from your hand into the Deck; \
    Special Summon this card, or place it in your Pendulum Zone.
● While this card is in your Monster Zone (Quick Effect): You can Tribute this card; \
    Special Summon 1 {0} from your {1}, but it cannot attack directly this turn.
"""
