[cyberse-digital-dragon]
id = 900006001
set = "cyber"
name = "Cyberse Digital Dragon"
type = "monster xyz effect"
attribute = "dark"
race = "cyberse"
level = 4
atk = 2500
def = 2000
effect = """\
2 Level 4 monsters
While you control a Link Monster, \
    monsters your opponent controls cannot target monsters you control for attacks, except this one, \
    also your opponent cannot target monsters you control with card effects, except this one. \
Once per turn (Quick Effect): You can detach 1 material from this card, \
    then target 1 face-up monster your opponent controls; \
    until the end of this turn, change its ATK to 0. \
If this card destroys an opponent's monster by battle: \
    Inflict damage to your opponent equal to the destroyed monster's original ATK. \
"""
strings = [
    "Make 1 monster ATK become 0",
    "Inflict damage equal to the destroyed monster's original ATK",
]

[storm-coder]
id = 900006002
set = "code-talker"
name = "Storm Coder"
type = "monster link effect"
attribute = "earth"
race = "cyberse"
link = 2
link-arrow = "bottom-left bottom-right"
atk = 1300
effect = """\
2 Cyberse monsters
(This card is always treated as a "Code Talker" card.)
If this card is Link Summoned: You can add from your Deck to your hand \
    1 monster that mentions a "Code Talker" card. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
If this card you control would be used as Link Material for a Cyberse monster, \
    you can also use 1 Cyberse monster in your hand as material. \
"""
strings = []

[stormcode-talker]
id = 900006003
set = "code-talker"
name = "Stormcode Talker"
type = "monster link effect"
attribute = "dark"
race = "cyberse"
link = 3
link-arrow = "bottom-left bottom bottom-right"
atk = 2300
effect = """\
2+ Cyberse monsters
If this card is Link Summoned: You can add from your Deck to your hand \
    1 card that mentions a "Code Talker" card. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
Cannot be attacked while in the Extra Monster Zone. \
Once while face-up the field: You can shuffle 1 Cyberse Link Monster this card points to into the Extra Deck, \
    and if you do, Special Summon 1 Link-3 "Code Talker" monster from your Extra Deck with a different name, \
    except "{CARD_NAME}" (this is treated as an Link Summon), \
    but that monster cannot attack this turn. \
"""
strings = ["Shuffle 1 Cyberse Link Monster to Link Summon 1 \"Code Talker\""]

[decode-dragon]
id = 900006004
name = "Decode Dragon"
type = "monster link effect"
attribute = "dark"
race = "cyberse"
link = 4
link-arrow = "top bottom-left bottom bottom-right"
atk = 2800
effect = """\
2+ Cyberse monsters
When your opponent activates a card or effect (Quick Effect): \
    You can destroy 1 monster this card points to, \
    and if you do, negate the activation. \
During the End Phase: \
    You can target 1 Cyberse monster in either GY that was destroyed this turn; \
    Special Summon it. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = [
    "Destroy 1 monster this card points to negate the activation",
    "Special Summon 1 Cyberse monster was destroyed this turn",
]

[firewall-dragon-negative]
id = 900006005
set = "firewall"
name = "Firewall Dragon Negative"
type = "monster link effect"
attribute = "dark"
race = "cyberse"
link = 6
link-arrow = "left right top bottom-left bottom bottom-right"
atk = 3500
effect = """\
3+ Cyberse monsters
(Quick Effect): You can target face-up cards in either GY and/or banishment \
    up to the number of different card types (Ritual, Fusion, Synchro, Xyz) you control and in your GY; \
    place them on the bottom of the Deck, \
    also all monsters your opponent currently controls lose 500 ATK for each shuffled card. \
If a monster this card points to is destroyed by battle, or sent to the GY: \
    You can Special Summon 1 Cyberse monster from your Deck. \
You can only use each effect of "{CARD_NAME}" once per turn. \
"""
strings = [
    "Shuffle cards in GY into the deck",
    "Special Summon a Cyberse monster from your Deck",
]

[firewall-dragon-pyrosoul]
id = 900006006
set = "firewall"
name = "Firewall Dragon Pyrosoul"
type = "monster link effect"
attribute = "light"
race = "cyberse"
link = 6
link-arrow = "left right top-left top top-right bottom"
atk = 4000
effect = """\
3+ Cyberse monsters with different Attributes
You can only control 1 "{CARD_NAME}". \
While this card is co-linked, \
    it and its co-linked cards cannot be destroyed, or banished, by your opponent's card effects, \
    these monsters gain 500 ATK for each number of cards co-linked to them, \
    also your opponent cannot target any of them with card effects. \
Once while face-up on the field: \
    You can pay 2000 LP, then Target 1 other "Firewall" Link Monster you control; \
    Place it face-up in your Spell & Trap Zone this card points to as a Link Spell, \
    and if you do, if this card is co-linked to that monster, \
    it gains the original effects of that monster. \
You can Target 1 other Link Monster you control this card points to; Destroy it, \
    and if you do, Special Summon 1 Cyberse Link Monster from your Extra Deck, \
    with Link Rating equal or lower than the destroyed monster's (this is treated as an Link Summon), \
You can only use each effect of "{CARD_NAME}" once per turn. \
"""
strings = [
    "Place 1 Link Monster as Link Spell",
    "Destroy to Link Summon 1 Cyberse monster",
]
