[yubel-the-ultimate-phantasmal-nightmare]
id = 900002007
rarity = "gold"
set = "phantasm"
name = "Yubel - The Ultimate Phantasmal Nightmare"
type = "monster fusion effect"
attribute = "dark"
race = "fiend"
level = 12
atk = 0
def = 0
effect = """\
"Yubel - The Ultimate Nightmare" + 1 "Phantasm" Fusion Monster
Must be Fusion Summoned with the above Fusion Materials. \
Control of it cannot switch. \
This card's name is also treated as "Armityle the Chaos Phantasm" while it is on the field. \
This card's battle position cannot be changed by card effects. \
Cannot be Tributed, or used as material for an Summon by your opponent. \
Cannot be destroyed by battle. \
The above effects cannot be negated. \
Your opponent takes any battle damage you would have taken from battles involving this card. \
At the end of the Damage Step, if this face-up Attack Position card battles an opponent's monster: \
    Inflict damage to your opponent equal to that monster's ATK, also destroy that monster. \
Once per turn (Quick Effect): \
    You can banish 1 face-up monster your opponent controls, and if you do, \
    Special Summon 1 "Phantasmal Nightmare Token" (Fiend/DARK/Level 12/ATK ?/DEF 0). \
    The Token's ATK/DEF become the original ATK/DEF of that monster, \
    also you take no damage from battles involving it. \
"""
strings = [
    "Inflict damage & destroy battling monster",
    "Banish 1 face-up monster & create token",
]

[phantasmal-nightmare-token]
id = 900002008
set = "phantasm"
name = "Phantasmal Nightmare Token"
type = "monster token"
attribute = "dark"
race = "fiend"
level = 12
atk = "?"
def = 0
effect = """\
Special Summoned with the effect of "Yubel - The Ultimate Phantasmal Nightmare". \
This Token's ATK/DEF become the original ATK/DEF of the banished monster, \
    also you take no damage from battles involving it. \
"""
strings = []
