[dragon-elysium]
id = 900007000
name = "Dragon's Elysium"
type = "spell field"
effect = """
While you control "Messiah, Supreme Deity of Dragons", \
    your opponent cannot target this card with card effects, \
    also it is unaffected by your opponent's card effects. \
    This effects cannot be negated. \
The effects of Link Pendulum Monster Cards you control cannot be negated. \
This card gains the original effects of all Continuous Spell/Trap attached to it. \
Once per turn: you can discard 1 card, then activate 1 of these effects;
● Send 1 Dragon monster from your Deck to the GY.
● Add 1 Level 4 or lower Dragon monster with the same Attribute as the discarded monster from your Deck to your hand.
● Attach 1 Dragon monster from your hand, Deck, or Extra Deck \
    to 1 "Messiah, Supreme Deity of Dragons" in your Monster Zone.
"""
strings = [
    "Discard to activate effect",
    "Send 1 Dragon to the GY",
    "Add 1 Level 4 or lower Dragon",
    "Attach 1 Dragon monster to \"Messiah, Supreme Deity of Dragons\"",
]

[messiah-deity]
id = 900007001
rarity = "gold"
name = "Messiah, Supreme Deity of Dragons"
type = "monster link pendulum effect"
attribute = "divine"
race = "creator-god"
link = 6
link-arrow = "top-left top-right left right bottom-left bottom-right"
scale = 13
atk = "?"
pendulum-effect = """\
Cannot be targeted by card effects, also unaffected by other card effects. \
    The above effects cannot be negated. \
The Pendulum Scale of card in your other Pendulum Zone become 0. \
During either player's turn, except the turn this card was placed Pendulum Zones (Quick Effect): \
    You can banish 6 other Dragon monsters with different Attributes from your hand, field, GY, Deck, and/or Extra Deck; \
    shuffle this card into the Extra Deck, and if you do, it becomes the Standby Phase of your next turn. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
effect = """\
Cannot be Link Summoned. \
Must be Special Summoned (from your Extra Deck face-down or Pendulum Zones) \
    by overlaying all Link Pendulum Monsters you control including at least 3 original Dragon monster. \
    You can only Special Summon "{CARD_NAME}" once per turn this way, \
    except the turn this card was placed Pendulum Zones. \
This card's Special Summon cannot be negated. \
You can only control 1 "{CARD_NAME}". \
Cannot be Tributed, or use as material for an Summon. \
Control of it cannot switch. \
When Special Summoned, other cards and effects cannot be activated, \
    also after that, you can move this card to another of your Main Monster Zones. \
This card's effects cannot be negated. \
This card's original ATK becomes to the number of cards attached to it x 1000. \
This card gains the original effects of all monsters attached to it. \
The above effects cannot be negated or be copied. \
(Quick Effect): You can destroy 2 Link Pendulum Monster Cards in your Pendulum Zones, and if you do, \
    add all other Pendulum Monsters that attached to this card, or in your GY to the Extra Deck face-up (if any), \
    also, place this card from your Monster Zone, GY, or Extra Deck face-up in your Pendulum Zone, \
    then, you can place 1 Pendulum Monster from your Deck in your Pendulum Zone. \
    This effect's activation and effect cannot be negated. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = [
    "Pay the cost?",
    "Shuffle this card into the Extra Deck & move to the Standby Phase of your next turn",
    "Move this card to another of your Main Monster Zones?",
    "Place this card in your Pendulum Zone",
    "Place 1 Pendulum Monster from your Deck in your Pendulum Zone?",
]

[messiah-origin]
id = 900007002
name = "Messiah, Origin Deity of Dragons"
type = "monster link pendulum effect"
attribute = "light"
race = "divine-beast"
link = 1
link-arrow = "bottom-right"
scale = 0
atk = 0
pendulum-effect = """\
{MESSIAH_BABY_PENDULUM_EFFECT} \
Pendulum Summons of your Dragon monsters cannot be negated. \
"""
effect = """\
{MESSIAH_BABY_MONSTER_EFFECT|WATER and WIND|hand or Deck} \
"""
strings = [
    "Add to Extra Deck",
    "Special Summon a Dragon from hand or Deck",
    "Place in Pendulum Zone",
]

[messiah-genesis]
id = 900007003
name = "Messiah, Genesis Deity of Dragons"
type = "monster link pendulum effect"
attribute = "dark"
race = "divine-beast"
link = 1
link-arrow = "bottom-left"
scale = 13
atk = 0
pendulum-effect = """\
{MESSIAH_BABY_PENDULUM_EFFECT} \
Your opponent cannot activate a Spell/Trap Card, or monster effect, when your Dragon monster(s) is Pendulum Summoned. \
"""
effect = """\
{MESSIAH_BABY_MONSTER_EFFECT|FIRE and EARTH|Deck or GY} \
"""
strings = [
    "Add to Extra Deck",
    "Special Summon a Dragon from Deck or GY",
    "Place in Pendulum Zone",
]

[dragon-deity-water]
id = 900007004
rarity = "gold"
name = "Sapphireoh, Dragon Deity of Ice Ages"
type = "monster link pendulum effect"
attribute = "water"
race = "dragon"
link = 5
link-arrow = "top-right right bottom-left bottom bottom-right"
scale = 11
atk = 3500
pendulum-effect = """\
{DRAGON_DEITY_PENDULUM_EFFECT|WATER} \
"""
effect = """\
{DRAGON_DEITY_MONSTER_EFFECT|WATER} \
This card and co-linked Pendulum Monsters you control cannot be destroyed by battle. \
    This effect cannot be negated. \
If this card attacks, your opponent cannot activate cards or effects until the end of the Damage Step. \
{DRAGON_DEITY_IGNITION_EFFECT|WATER|the following effect}
● Choose 1 other card on the field, except a card(s) already affected by "{CARD_NAME}", \
    it cannot activate its effect, also if you choose a monster, \
    it cannot change its battle position or declare an attack, and change its ATK/DEF to 0 (if it is face-up).
"""
strings = ["Block 1 card on the field", "Affected by effect \"{CARD_NAME}\""]

[dragon-deity-fire]
id = 900007005
rarity = "gold"
name = "Rubyoh, Dragon Deity of Fire Storms"
type = "monster link pendulum effect"
attribute = "fire"
race = "dragon"
link = 5
link-arrow = "top-left left bottom-left bottom bottom-right"
scale = 11
atk = 3500
pendulum-effect = """\
{DRAGON_DEITY_PENDULUM_EFFECT|FIRE} \
"""
effect = """\
{DRAGON_DEITY_MONSTER_EFFECT|FIRE} \
This card and co-linked Pendulum Monsters you control cannot be destroyed by card effects. \
    This effect cannot be negated. \
If this card destroys a monster(s) by battle or by its effect: \
    You can inflict damage to your opponent equal to that destroyed monster's original ATK. \
{DRAGON_DEITY_IGNITION_EFFECT|FIRE|the following effect}
● Destroy 1 other card on the field.
"""
strings = [
    "Inflict damage equal to destroyed monster's original ATK",
    "Destroy 1 card on the field",
]

[dragon-deity-wind]
id = 900007006
rarity = "gold"
name = "Emeraldoh, Dragon Deity of Eternal Lifes"
type = "monster link pendulum effect"
attribute = "wind"
race = "dragon"
link = 5
link-arrow = "top-right left right bottom bottom-right"
scale = 11
atk = 3500
pendulum-effect = """\
{DRAGON_DEITY_PENDULUM_EFFECT|WIND} \
"""
effect = """\
{DRAGON_DEITY_MONSTER_EFFECT|WIND} \
This card and co-linked Pendulum Monsters you control are unaffected by your opponent's activated Spell Cards or effects. \
    This effect cannot be negated. \
Each time you Special Summon a monster(s) face-up, you can gain LP equal to that monster's ATK. \
{DRAGON_DEITY_IGNITION_EFFECT|WIND|the following effect}
● Special Summon 1 monster from hand or either GY to either player's field, except "{CARD_NAME}".
"""
strings = [
    "Gain LP equal to Summoned monster's ATK?",
    "Special Summon 1 monster from hand or either GY",
    "Special Summon to your field",
    "Special Summon to your opponent's field",
]

[dragon-deity-earth]
id = 900007007
rarity = "gold"
name = "Amberoh, Dragon Deity of Ancient Continents"
type = "monster link pendulum effect"
attribute = "earth"
race = "dragon"
link = 5
link-arrow = "top-left left right bottom-left bottom"
scale = 11
atk = 3500
pendulum-effect = """\
{DRAGON_DEITY_PENDULUM_EFFECT|EARTH} \
"""
effect = """\
{DRAGON_DEITY_MONSTER_EFFECT|EARTH} \
This card and co-linked Pendulum Monsters you control are unaffected by your opponent's activated Trap Cards or effects. \
    This effect cannot be negated. \
Each time your opponent Special Summons a monster(s), you can draw 1 card. \
{DRAGON_DEITY_IGNITION_EFFECT|EARTH|1 of these effects}
● Send 1 card from your hand, Deck, Extra Deck to the GY, except a Link Pendulum Monster.
● Send up to 10 cards from the top of your opponent's Deck to the GY.
"""
strings = [
    "Draw 1 card?",
    "Send card to the GY",
    "Send 1 card from your hand, Deck, or Extra Deck to GY",
    "Send cards from the top of your opponent's Deck to GY",
    "Declare a number of cards to send",
]

[dragon-deity-light]
id = 900007008
rarity = "gold"
name = "Diamondoh, Dragon Deity of Miracle Symphonies"
type = "monster link pendulum effect"
attribute = "light"
race = "dragon"
link = 5
link-arrow = "top left right bottom-right bottom"
scale = 11
atk = 3500
pendulum-effect = """\
{DRAGON_DEITY_PENDULUM_EFFECT|LIGHT} \
"""
effect = """\
{DRAGON_DEITY_MONSTER_EFFECT|LIGHT} \
This card and co-linked Pendulum Monsters you control cannot be banished by card effects. \
    This effect cannot be negated. \
When your opponent activates a card or effect (Quick Effect): \
    You can negate that effect, and if you do, destroy that card. \
    You can only activate this effect of "{CARD_NAME}" in response to each card type (Monster, Spell, or Trap) once per turn. \
{DRAGON_DEITY_IGNITION_EFFECT|LIGHT|the following effect}
● Roll a six-sided die, shuffle other cards on the fields, GYs, and banishments into the Decks, up to the result, \
    and if you do, this card gains 1000 ATK for each shuffled card until the end of the next turn. \
"""
strings = [
    "Negate the effect & destroy",
    "Used \"{CARD_NAME}\"'s effect to negate Monster Card",
    "Used \"{CARD_NAME}\"'s effect to negate Spell Card",
    "Used \"{CARD_NAME}\"'s effect to negate Trap Card",
    "Roll a die and shuffle cards into the Decks",
]

[dragon-deity-dark]
id = 900007009
rarity = "gold"
name = "Obsidianoh, Dragon Deity of Event Horizons"
type = "monster link pendulum effect"
attribute = "dark"
race = "dragon"
link = 5
link-arrow = "top left right bottom-left bottom"
scale = 11
atk = 3500
pendulum-effect = """\
{DRAGON_DEITY_PENDULUM_EFFECT|DARK} \
"""
effect = """\
{DRAGON_DEITY_MONSTER_EFFECT|DARK} \
Your opponent cannot target this card and co-linked Pendulum Monsters you control with card effects. \
    This effect cannot be negated. \
Once per turn, you can send 1 Monster Card you control that is equipped to this card to the GY; \
    until the End Phase, replace this effect with that monster's original effects, \
    also for the rest of this turn, this card can attack all monsters your opponent controls, once each. \
{DRAGON_DEITY_IGNITION_EFFECT|DARK|the following effect}
● Equip 1 monster your opponent control or in either GY to this card as an Equip Spell that gives this card 1000 ATK.
"""
strings = [
    "Send 1 equipped monster to GY to gain effects",
    "Can attack all monsters your opponent controls",
    "Equip 1 monster to this card",
]

[dragon-deity-baby-water]
id = 900007010
name = "Lapison, Dragon of Frosts"
type = "monster link effect"
attribute = "water"
race = "dragon"
link = 3
link-arrow = "right bottom bottom-right"
atk = 2100
effect = """\
{DRAGON_DEITY_BABY_MONSTER_EFFECT|WATER} \
"""
strings = [
    "Special Summon the added monster?",
    "Return 1 non-Link WATER or Dragon to the Deck?",
]

[dragon-deity-baby-fire]
id = 900007011
name = "Garneton, Dragon of Embers"
type = "monster link effect"
attribute = "fire"
race = "dragon"
link = 3
link-arrow = "left bottom-left bottom"
atk = 2100
effect = """\
{DRAGON_DEITY_BABY_MONSTER_EFFECT|FIRE} \
"""
strings = [
    "Special Summon the added monster?",
    "Return 1 non-Link FIRE or Dragon to the Deck?",
]

[dragon-deity-baby-wind]
id = 900007012
name = "Peridoton, Dragon of Spirits"
type = "monster link effect"
attribute = "wind"
race = "dragon"
link = 3
link-arrow = "right bottom bottom-right"
atk = 2100
effect = """\
{DRAGON_DEITY_BABY_MONSTER_EFFECT|WIND} \
"""
strings = [
    "Special Summon the added monster?",
    "Return 1 non-Link WIND or Dragon to the Deck?",
]

[dragon-deity-baby-earth]
id = 900007013
name = "Topazon, Dragon of Gorges"
type = "monster link effect"
attribute = "earth"
race = "dragon"
link = 3
link-arrow = "left bottom-left bottom"
atk = 2100
effect = """\
{DRAGON_DEITY_BABY_MONSTER_EFFECT|EARTH} \
"""
strings = [
    "Special Summon the added monster?",
    "Return 1 non-Link EARTH or Dragon to the Deck?",
]

[dragon-deity-baby-light]
id = 900007014
name = "Pearlon, Dragon of Wishes"
type = "monster link effect"
attribute = "light"
race = "dragon"
link = 3
link-arrow = "right bottom bottom-right"
atk = 2100
effect = """\
{DRAGON_DEITY_BABY_MONSTER_EFFECT|LIGHT} \
"""
strings = [
    "Special Summon the added monster?",
    "Return 1 non-Link LIGHT or Dragon to the Deck?",
]

[dragon-deity-baby-dark]
id = 900007015
name = "Onyxon, Dragon of Voids"
type = "monster link effect"
attribute = "dark"
race = "dragon"
link = 3
link-arrow = "left bottom-left bottom"
atk = 2100
effect = """\
{DRAGON_DEITY_BABY_MONSTER_EFFECT|DARK} \
"""
strings = [
    "Special Summon the added monster?",
    "Return 1 non-Link DARK or Dragon to the Deck?",
]

[dragon-ruler-light]
id = 900007016
name = "Halo, Dragon Ruler of Shines"
type = "monster effect"
attribute = "light"
race = "dragon"
level = 7
atk = 2500
def = 2100
effect = """\
If this card is in your hand or GY: \
    You can banish a total of 2 LIGHT and/or Dragon monsters from your hand and/or GY, except this card; \
    Special Summon this card. \
During your opponent's End Phase, if you control this Special Summoned card: \
    Return it to the hand. \
You can discard this card and 1 LIGHT monster to the GY, \
    then target 1 your banished monster; add it to your hand. \
If this card is banished: You can add 1 LIGHT Dragon monster from your Deck to your hand. \
You can only use 1 "{CARD_NAME}" effect per turn, and only once that turn. \
"""
strings = ["Return to the hand", "Return 1 banished card to the hand"]

[dragon-ruler-dark]
id = 900007017
name = "Abyss, Dragon Ruler of Darknesses"
type = "monster effect"
attribute = "dark"
race = "dragon"
level = 7
atk = 2900
def = 1700
effect = """\
If this card is in your hand or GY: \
    You can banish a total of 2 DARK and/or Dragon monsters from your hand and/or GY, except this card; \
    Special Summon this card. \
During your opponent's End Phase, if you control this Special Summoned card: \
    Return it to the hand. \
You can discard this card and 1 DARK monster to the GY, \
    then target 1 card on the field; banish it. \
If this card is banished: You can add 1 DARK Dragon monster from your Deck to your hand. \
You can only use 1 "{CARD_NAME}" effect per turn, and only once that turn. \
"""
strings = ["Return to the hand", "Banish 1 card on the field"]

[dragon-ruler-baby-light]
id = 900007018
name = "Ray, Dragon Ruler of Radiances"
type = "monster effect"
attribute = "light"
race = "dragon"
level = 4
atk = 1700
def = 1400
effect = """\
You can discard this card and 1 Dragon or LIGHT monster; \
    Special Summon 1 "Halo, Dragon Ruler of Shines" from your Deck, \
    but it cannot attack this turn. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = []

[dragon-ruler-baby-dark]
id = 900007019
name = "Umbra, Dragon Ruler of Shadows"
type = "monster effect"
attribute = "dark"
race = "dragon"
level = 3
atk = 1300
def = 700
effect = """\
You can discard this card and 1 Dragon or DARK monster; \
    Special Summon 1 "Abyss, Dragon Ruler of Darknesses" from your Deck, \
    but it cannot attack this turn. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = []
