[messiah-deity]
id = 900007001
rarity = "gold"
name = "Messiah, Supreme Deity of Dragons"
type = "monster link pendulum effect"
attribute = "divine"
race = "dragon"
link = 6
link-arrow = "top-left top-right left right bottom-left bottom-right"
scale = 13
atk = "?"
pendulum-effect = """\
"""
effect = """\
"""
strings = []

[messiah-origin]
id = 900007002
name = "Messiah, Origin of Dragons"
type = "monster link pendulum effect"
attribute = "light"
race = "dragon"
link = 1
link-arrow = "bottom-right"
scale = 0
atk = 0
pendulum-effect = """\
{MESSIAH_BABY_PENDULUM_EFFECT} \
"""
effect = """\
{MESSIAH_BABY_MONSTER_EFFECT|FIRE and WIND|hand or Deck} \
"""
strings = [
    "Add to Extra Deck",
    "Special Summon a Dragon from hand or Deck",
    "Place in Pendulum Zone",
]

[messiah-genesis]
id = 900007003
name = "Messiah, Genesis of Dragons"
type = "monster link pendulum effect"
attribute = "dark"
race = "dragon"
link = 1
link-arrow = "bottom-left"
scale = 13
atk = 0
pendulum-effect = """\
{MESSIAH_BABY_PENDULUM_EFFECT} \
"""
effect = """\
{MESSIAH_BABY_MONSTER_EFFECT|WATER and EARTH|Deck or GY} \
"""
strings = [
    "Add to Extra Deck",
    "Special Summon a Dragon from Deck or GY",
    "Place in Pendulum Zone",
]

[dragon-deity-fire]
id = 900007004
rarity = "gold"
name = "Rubyoh, Dragon Deity of Fire Storms"
type = "monster link pendulum effect"
attribute = "fire"
race = "dragon"
link = 5
link-arrow = "top-right right bottom-left bottom bottom-right"
scale = 11
atk = 4000
pendulum-effect = """\
{DRAGON_DEITY_PENDULUM_EFFECT|FIRE} \
"""
effect = """\
{DRAGON_DEITY_MONSTER_EFFECT|FIRE} \
This card and other co-linked Link-5 or higher Dragon monsters you control cannot be destroyed by card effects, \
    also they are unaffected by card effects that prevent them from attacking, also their attacks cannot be negated. \
Once per turn, you can banish 1 FIRE monster from your hand or GY; \
    destroy 1 other card on the field, then, if you destroyed a face-up monster, \
    you can inflict damage to your opponent equal to the ATK it had on the field. \
    If this card is Special Summoned by its own Pendulum Effect: You can also apply this effect. \
"""
strings = [
    "Destroy 1 card on the field",
    "Inflict damage to your opponent equal to the destroyed monster's ATK?",
]

[dragon-deity-water]
id = 900007005
rarity = "gold"
name = "Sapphireoh, Dragon Deity of Ice Ages"
type = "monster link pendulum effect"
attribute = "water"
race = "dragon"
link = 5
link-arrow = "top-left left bottom-left bottom bottom-right"
scale = 11
atk = 4000
pendulum-effect = """\
{DRAGON_DEITY_PENDULUM_EFFECT|WATER} \
"""
effect = """\
{DRAGON_DEITY_MONSTER_EFFECT|WATER} \
This card and other co-linked Link-5 or higher Dragon monsters you control cannot be destroyed by battle, \
    also you take no damage from battles involving them. \
Once per turn, you can banish 1 WATER monster from your hand or GY; \
    choose 1 other card on the field, except a card(s) already affected by "{CARD_NAME}", \
    it cannot activate its effect, also if you choose a monster, it cannot change its battle position or declare an attack, \
    and change its ATK to 0 (if it is face-up), and if you do, \
    this card gains ATK equal to that monster's ATK until the end of this turn, \
    If this card is Special Summoned by its own Pendulum Effect: You can also apply this effect. \
"""
strings = ["Block 1 card on the field", "Affected by effect \"{CARD_NAME}\""]

[dragon-deity-wind]
id = 900007006
rarity = "gold"
name = "Emeraldoh, Dragon Deity of Life Cycles"
type = "monster link pendulum effect"
attribute = "wind"
race = "dragon"
link = 5
link-arrow = "top-right left right bottom bottom-right"
scale = 11
atk = 4000
pendulum-effect = """\
{DRAGON_DEITY_PENDULUM_EFFECT|WIND} \
"""
effect = """\
{DRAGON_DEITY_MONSTER_EFFECT|WIND} \
This card and other co-linked Link-5 or higher Dragon monsters you control cannot be sent to the GY, \
    also they are unaffected by your opponent's activated Spell Cards or effects. \
"""
strings = []

[dragon-deity-earth]
id = 900007007
rarity = "gold"
name = "Amberoh, Dragon Deity of World Continents"
type = "monster link pendulum effect"
attribute = "earth"
race = "dragon"
link = 5
link-arrow = "top-left left right bottom-left bottom"
scale = 11
atk = 4000
pendulum-effect = """\
{DRAGON_DEITY_PENDULUM_EFFECT|EARTH} \
"""
effect = """\
{DRAGON_DEITY_MONSTER_EFFECT|EARTH} \
This card and other co-linked Link-5 or higher Dragon monsters you control cannot be returned to the Extra Deck, \
    also they are unaffected by your opponent's activated Trap Cards or effects. \
"""
strings = []

[dragon-deity-light]
id = 900007008
rarity = "gold"
name = "Diamondoh, Dragon Deity of Miracle Symphonies"
type = "monster link pendulum effect"
attribute = "light"
race = "dragon"
link = 5
link-arrow = "top left right bottom-right bottom"
scale = 11
atk = 4000
pendulum-effect = """\
{DRAGON_DEITY_PENDULUM_EFFECT|LIGHT} \
"""
effect = """\
{DRAGON_DEITY_MONSTER_EFFECT|LIGHT} \
The effects of this card and other co-linked Link-5 or higher Dragon monsters you control cannot be negated. \
Your opponent cannot target face-up Spells/Traps you control with card effects, \
    also they cannot be destroyed, or banished, by your opponent's card effects. \
"""
strings = []

[dragon-deity-dark]
id = 900007009
rarity = "gold"
name = "Obsidianoh, Dragon Deity of Event Horizons"
type = "monster link pendulum effect"
attribute = "dark"
race = "dragon"
link = 5
link-arrow = "top left right bottom-left bottom"
scale = 11
atk = 4000
pendulum-effect = """\
{DRAGON_DEITY_PENDULUM_EFFECT|DARK} \
"""
effect = """\
{DRAGON_DEITY_MONSTER_EFFECT|DARK} \
this card and other co-linked Link-5 or higher Dragon monsters you control cannot be banished by card effects, \
    also your opponent cannot target them with card effects. \
"""
strings = []

[dragon-deity-baby-fire]
id = 900007010
name = "Garneton, Dragon of Embers"
type = "monster link effect"
attribute = "fire"
race = "dragon"
link = 3
link-arrow = "right bottom bottom-right"
atk = 2000
effect = """\
{DRAGON_DEITY_BABY_MONSTER_EFFECT|FIRE} \
"""
strings = [
    "Special Summon the added monster?",
    "Add 1 banished non-Link FIRE Dragon monster to hand?",
]

[dragon-deity-baby-water]
id = 900007011
name = "Lapison, Dragon of Frosts"
type = "monster link effect"
attribute = "water"
race = "dragon"
link = 3
link-arrow = "left bottom-left bottom"
atk = 2000
effect = """\
{DRAGON_DEITY_BABY_MONSTER_EFFECT|WATER} \
"""
strings = [
    "Special Summon the added monster?",
    "Add 1 banished non-Link WATER Dragon monster to hand?",
]

[dragon-deity-baby-wind]
id = 900007012
name = "Peridoton, Dragon of Spirits"
type = "monster link effect"
attribute = "wind"
race = "dragon"
link = 3
link-arrow = "right bottom bottom-right"
atk = 2000
effect = """\
{DRAGON_DEITY_BABY_MONSTER_EFFECT|WIND} \
"""
strings = [
    "Special Summon the added monster?",
    "Add 1 banished non-Link WIND Dragon monster to hand?",
]

[dragon-deity-baby-earth]
id = 900007013
name = "Topazon, Dragon of Gorges"
type = "monster link effect"
attribute = "earth"
race = "dragon"
link = 3
link-arrow = "left bottom-left bottom"
atk = 2000
effect = """\
{DRAGON_DEITY_BABY_MONSTER_EFFECT|EARTH} \
"""
strings = [
    "Special Summon the added monster?",
    "Add 1 banished non-Link EARTH Dragon monster to hand?",
]

[dragon-deity-baby-light]
id = 900007014
name = "Pearlon, Dragon of Wishes"
type = "monster link effect"
attribute = "light"
race = "dragon"
link = 3
link-arrow = "right bottom bottom-right"
atk = 2000
effect = """\
{DRAGON_DEITY_BABY_MONSTER_EFFECT|LIGHT} \
"""
strings = [
    "Special Summon the added monster?",
    "Add 1 banished non-Link LIGHT Dragon monster to hand?",
]

[dragon-deity-baby-dark]
id = 900007015
name = "Onyxon, Dragon of Voids"
type = "monster link effect"
attribute = "dark"
race = "dragon"
link = 3
link-arrow = "left bottom-left bottom"
atk = 2000
effect = """\
{DRAGON_DEITY_BABY_MONSTER_EFFECT|DARK} \
"""
strings = [
    "Special Summon the added monster?",
    "Add 1 banished non-Link DARK Dragon monster to hand?",
]

[dragon-ruler-light]
id = 900007016
name = "Halo, Dragon Ruler of Shines"
type = "monster effect"
attribute = "light"
race = "dragon"
level = 7
atk = 2500
def = 2100
effect = """\
If this card is in your hand or GY: \
    You can banish a total of 2 LIGHT and/or Dragon monsters from your hand and/or GY, except this card; \
    Special Summon this card. \
During your opponent's End Phase, if you control this Special Summoned card: \
    Return it to the hand. \
You can discard this card and 1 LIGHT monster to the GY, \
    then target 1 your banished monster; add it to your hand. \
If this card is banished: You can add 1 LIGHT Dragon monster from your Deck to your hand. \
You can only use 1 "{CARD_NAME}" effect per turn, and only once that turn. \
"""
strings = ["Return to the hand", "Banish 1 card on the field"]

[dragon-ruler-dark]
id = 900007017
name = "Abyss, Dragon Ruler of Darknesses"
type = "monster effect"
attribute = "dark"
race = "dragon"
level = 7
atk = 2900
def = 1700
effect = """\
If this card is in your hand or GY: \
    You can banish a total of 2 DARK and/or Dragon monsters from your hand and/or GY, except this card; \
    Special Summon this card. \
During your opponent's End Phase, if you control this Special Summoned card: \
    Return it to the hand. \
You can discard this card and 1 DARK monster to the GY, \
    then target 1 card on the field; banish it. \
If this card is banished: You can add 1 DARK Dragon monster from your Deck to your hand. \
You can only use 1 "{CARD_NAME}" effect per turn, and only once that turn. \
"""
strings = ["Return to the hand", "Banish 1 card on the field"]

[dragon-ruler-baby-light]
id = 900007018
name = "Ray, Dragon Ruler of Radiances"
type = "monster effect"
attribute = "light"
race = "dragon"
level = 4
atk = 1700
def = 1400
effect = """\
You can discard this card and 1 Dragon or LIGHT monster; \
    Special Summon 1 "Halo, Dragon Ruler of Shines" from your Deck, \
    but it cannot attack this turn. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = []

[dragon-ruler-baby-dark]
id = 900007019
name = "Umbra, Dragon Ruler of Shadows"
type = "monster effect"
attribute = "dark"
race = "dragon"
level = 3
atk = 1300
def = 700
effect = """\
You can discard this card and 1 Dragon or DARK monster; \
    Special Summon 1 "Abyss, Dragon Ruler of Darknesses" from your Deck, \
    but it cannot attack this turn. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = []
