[mesaia-deity]
id = 900007001
rarity = "gold"
name = "Mesaia, Supreme Deity of Dragons"
type = "monster link pendulum effect"
attribute = "divine"
race = "dragon"
link = 5
link-arrow = "left right bottom-left bottom bottom-right"
scale = 13
atk = 5000
pendulum-effect = """\
"""
effect = """\
"""
strings = []

[mesaia-origin]
id = 900007002
name = "Mesaia, Origin of Dragons"
type = "monster pendulum effect"
attribute = "divine"
race = "dragon"
level = 1
scale = 0
atk = 0
def = 0
pendulum-effect = """\
You cannot Pendulum Summon monsters, except Dragon monsters. This effect cannot be negated. \
If you Pendulum Summon a monster(s): Return this card from the Pendulum Zone to the hand. \
"""
effect = """\
You can reveal 1 other non-DIVINE Dragon monster in your hand; \
    until the end of this turn, this card in your hand becomes revealed \
    and its Attribute become the same as that monster's. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
{DRAGON_RULER_BABY_SHUFFLE_EFFECT} \
"""
strings = ["Return to the hand", "Change Attribute", "Revealed"]

[mesaia-genesis]
id = 900007003
name = "Mesaia, Genesis of Dragons"
type = "monster pendulum effect"
attribute = "divine"
race = "dragon"
level = 1
scale = 13
atk = 0
def = 0
pendulum-effect = """\
You cannot Pendulum Summon monsters, except Dragon monsters. This effect cannot be negated. \
If you Pendulum Summon a monster(s): Return this card from the Pendulum Zone to the hand. \
"""
effect = """\
You can reveal 1 other non-DIVINE Dragon monster in your hand; \
    until the end of this turn, this card in your hand becomes revealed \
    and its Attribute become the same as that monster's. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
{DRAGON_RULER_BABY_SHUFFLE_EFFECT} \
"""
strings = ["Return to the hand", "Change Attribute", "Revealed"]

[kagero-firestorms]
id = 900007004
rarity = "gold"
name = "Kagero, Dragon Emperor of Firestorms"
type = "monster fusion pendulum effect"
attribute = "fire"
race = "dragon"
level = 10
scale = 12
atk = 3800
def = 2200
pendulum-effect = """\
{DRAGON_EMPEROR_PENDULUM_EFFECT|FIRE} \
"""
effect = """\
1 Level 7 or higher Dragon monster + 1 FIRE mosnter
This face-down card in the Extra Deck must first be either Fusion Summoned, \
    or Special Summoned by Tributing the above cards you control. \
{DRAGON_EMPEROR_MONSTER_EFFECT} \
This card and other Dragon monsters you control cannot be destroyed, \
    or banished, by your opponent's card effects. \
You can banish 1 FIRE monster from your hand or GY, then target 1 other card on the field; \
    destroy it, then if you destroyed a face-up monster, \
    you can inflict damage to your opponent equal to the ATK it had on the field. \
    If this card is Special Summoned by its own Pendulum Effect: You can also apply this effect. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = [
    "Destroy 1 card on the field",
    "Inflict damage to your opponent equal to the destroyed monster's ATK?",
]

[kagero-embers]
id = 900007005
name = "Kagero, Dragon Ruler of Embers"
type = "monster effect"
attribute = "fire"
race = "dragon"
level = 4
atk = 1500
def = 1000
effect = """\
{DRAGON_RULER_BABY_SHUFFLE_EFFECT} \
"""
strings = []

[kidisuto-continents]
id = 900007006
rarity = "gold"
name = "Kidisuto, Dragon Emperor of Continents"
type = "monster fusion pendulum effect"
attribute = "earth"
race = "dragon"
level = 10
scale = 1
atk = 3300
def = 2700
pendulum-effect = """\
"""
effect = """\
"""
strings = []

[kidisuto-gorges]
id = 900007007
name = "Kidisuto, Dragon Ruler of Gorges"
type = "monster effect"
attribute = "earth"
race = "dragon"
level = 4
atk = 600
def = 1900
effect = """\
{DRAGON_RULER_BABY_SHUFFLE_EFFECT} \
"""
strings = []

[akuafosu-glacials]
id = 900007008
rarity = "gold"
name = "Akuafosu, Dragon Emperor of Glacials"
type = "monster synchro pendulum effect"
attribute = "water"
race = "dragon"
level = 10
scale = 12
atk = 3500
def = 2500
pendulum-effect = """\
"""
effect = """\
"""
strings = []

[akuafosu-frosts]
id = 900007009
name = "Akuafosu, Dragon Ruler of Frosts"
type = "monster effect"
attribute = "water"
race = "dragon"
level = 3
atk = 1400
def = 1100
effect = """\
{DRAGON_RULER_BABY_SHUFFLE_EFFECT} \
"""
strings = []

[nekutaru-lifes]
id = 900007010
rarity = "gold"
name = "Nekutaru, Dragon Emperor of Lifes"
type = "monster synchro pendulum effect"
attribute = "wind"
race = "dragon"
level = 10
scale = 1
atk = 3000
def = 3000
pendulum-effect = """\
"""
effect = """\
"""
strings = []

[nekutaru-spirits]
id = 900007011
name = "Nekutaru, Dragon Ruler of Spirits"
type = "monster effect"
attribute = "wind"
race = "dragon"
level = 3
atk = 800
def = 1700
effect = """\
{DRAGON_RULER_BABY_SHUFFLE_EFFECT} \
"""
strings = []

[roiyaru-miracles]
id = 900007012
rarity = "gold"
name = "Roiyaru, Dragon Emperor of Miracles"
type = "monster xyz pendulum effect"
attribute = "light"
race = "dragon"
level = 10
scale = 12
atk = 4000
def = 2000
pendulum-effect = """\
"""
effect = """\
"""
strings = []

[roiyaru-wishes]
id = 900007013
name = "Roiyaru, Dragon Ruler of Wishes"
type = "monster effect"
attribute = "light"
race = "dragon"
level = 4
atk = 1900
def = 600
effect = """\
{DRAGON_RULER_BABY_SHUFFLE_EFFECT} \
"""
strings = []

[sutabeida-horizons]
id = 900007014
rarity = "gold"
name = "Sutabeida, Dragon Emperor of horizons"
type = "monster xyz pendulum effect"
attribute = "dark"
race = "dragon"
level = 10
scale = 1
atk = 4000
def = 2000
pendulum-effect = """\
"""
effect = """\
"""
strings = []

[sutabeida-voids]
id = 900007015
name = "Sutabeida, Dragon Ruler of voids"
type = "monster effect"
attribute = "dark"
race = "dragon"
level = 4
atk = 1900
def = 600
effect = """\
{DRAGON_RULER_BABY_SHUFFLE_EFFECT} \
"""
strings = []

[halo-shines]
id = 900007016
name = "Halo, Dragon Ruler of Shines"
type = "monster effect"
attribute = "light"
race = "dragon"
level = 7
atk = 2500
def = 2100
effect = """\
If this card is in your hand or GY:\
    You can banish a total of 2 LIGHT and/or Dragon monsters from your hand and/or GY, except this card; \
    Special Summon this card. \
During your opponent's End Phase, if you control this Special Summoned card: \
    Return it to the hand. \
You can discard this card and 1 LIGHT monster to the GY, \
    then target 1 monster in your banishment; add it to your hand. \
If this card is banished: You can add 1 LIGHT Dragon monster from your Deck to your hand. \
You can only use 1 "{CARD_NAME}" effect per turn, and only once that turn. \
"""
strings = ["Return to the hand", "Add 1 banished monster to the hand"]

[ray-radiances]
id = 900007017
name = "Ray, Dragon Ruler of Radiances"
type = "monster effect"
attribute = "light"
race = "dragon"
level = 4
atk = 1700
def = 1400
effect = """\
You can discard this card and 1 Dragon or LIGHT monster; \
    Special Summon 1 "Halo, Dragon Ruler of Shines" from your Deck, \
    but it cannot attack this turn. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = []

[abyss-darknesses]
id = 900007018
name = "Abyss, Dragon Ruler of Darknesses"
type = "monster effect"
attribute = "dark"
race = "dragon"
level = 7
atk = 2900
def = 1700
effect = """\
If this card is in your hand or GY:\
    You can banish a total of 2 DARK and/or Dragon monsters from your hand and/or GY, except this card; \
    Special Summon this card. \
During your opponent's End Phase, if you control this Special Summoned card: \
    Return it to the hand. \
You can discard this card and 1 DARK monster to the GY, \
    then target 1 card on the field; banish it. \
If this card is banished: You can add 1 DARK Dragon monster from your Deck to your hand. \
You can only use 1 "{CARD_NAME}" effect per turn, and only once that turn. \
"""
strings = ["Return to the hand", "Banish 1 card on the field"]

[umbra-shadows]
id = 900007019
name = "Umbra, Dragon Ruler of Shadows"
type = "monster effect"
attribute = "dark"
race = "dragon"
level = 3
atk = 1300
def = 700
effect = """\
You can discard this card and 1 Dragon or DARK monster; \
    Special Summon 1 "Abyss, Dragon Ruler of Darknesses" from your Deck, \
    but it cannot attack this turn. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = []
