DRAGON_EMPEROR_PENDULUM_EFFECT = """\
During either turn, except the End Phase (Quick Effect): \
    You can banish 2 {0} and/or Dragon monsters from your hand and/or GY; \
    Special Summon this card from the Pendulum Zone. \
    You can only use this effect of "{CARD_NAME}" once per turn.\
"""

DRAGON_EMPEROR_MONSTER_EFFECT = """\
This card's Special Summon cannot be negated. \
You can only control 1 "{CARD_NAME}". \
Your opponent cannot Tribute this card, or use it as material for an Summon. \
Its battle position cannot be changed by card effects. \
Its control cannot switch. \
The above effects cannot be negated or be copied. \
If this card in the Monster Zone is destroyed: You can place this card in your Pendulum Zone.\
"""
