DRAGON_DEITY_PENDULUM_EFFECT = """\
During either turn, except the End Phase (Quick Effect): \
    You can banish 2 {0} and/or Dragon monsters from your hand and/or GY; \
    Special Summon this card from the Pendulum Zone. \
    You can only use this effect of "{CARD_NAME}" once per turn.\
"""

DRAGON_DEITY_MONSTER_EFFECT = """\
3+ monsters, including a {0} Dragon monster
This face-down card in the Extra Deck must first be Link Summoned. \
If you can Pendulum Summon Level 10, you can Pendulum Summon this face-up card in your Extra Deck. \
This card's Special Summon cannot be negated. \
You can only control 1 "{CARD_NAME}". \
Your opponent cannot Tribute this card, or use it as material for an Summon. \
Its battle position cannot be changed by card effects. \
Its control cannot switch. \
The above effects cannot be negated or be copied. \
If this card in the Monster Zone is destroyed: You can place this card in your Pendulum Zone.\
"""

DRAGON_DEITY_BABY_MONSTER_EFFECT = """\
2+ Dragon monsters, including a {0} monster
If this card is Link Summoned: \
    You can either add to your hand or Special Summon \
    1 Level 4 or lower {0} Dragon monster from your Deck. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
Once per turn, during the End Phase of the turn this card was banished: \
    Shuffle this banished card into the Deck, \
    then you can add 1 banished non-Link {0} Dragon monster to your hand.\
"""

MESSIAH_BABY_PENDULUM_EFFECT = """\
You cannot Pendulum Summon monsters, except Dragon monsters. This effects cannot be negated. \
If you Pendulum Summon a monster(s): Add this card to your Extra Deck face-up.\
"""

MESSIAH_BABY_MONSTER_EFFECT = """\
1 non-Link Dragon monster
The Attribute of this card is also treated as {0} \
    while it is face-up on the field or in GY. \
    This effect cannot be negated. \
You can Tribute this card and discard 1 Dragon monster; \
    Special Summon from your {1}, \
    1 Dragon monster that can be Normal Summoned/Set \
    with the same Attribute as the discarded monster. \
During the Main Phase, except the turn this card was added to the Extra Deck face-up: \
    You can banish 1 Dragon monster from your hand or GY; \
    Place this face-up card from your Extra Deck in your Pendulum Zone. \
You can only use 1 "{CARD_NAME}" effect per turn, and only once that turn.\
"""
