DRAGON_DEITY_PENDULUM_EFFECT = """\
Your opponent cannot target this card with card effects. \
During either turn, except the End Phase (Quick Effect): \
    You can banish 2 {0} and/or Dragon monsters from your hand and/or GY; \
    Special Summon this card from the Pendulum Zone. \
    You can only use this effect of "{CARD_NAME}" once per turn.\
"""

DRAGON_DEITY_MONSTER_EFFECT = """\
3+ monsters, including a {0} monster
Cannot be Special Summoned, except by its owner. \
Must first be Link Summoned. \
If you can Pendulum Summon Level 10, you can Pendulum Summon this face-up card in your Extra Deck. \
This card's Special Summon cannot be negated. \
You can only control 1 "{CARD_NAME}". \
If this card in the Monster Zone is destroyed: You can place it in your Pendulum Zone.\
"""

DRAGON_DEITY_BABY_MONSTER_EFFECT = """\
2+ Dragon monsters, including a {0} monster
If this card is Link Summoned: \
    You can add 1 Level 7 or lower {0} Dragon monster from your Deck to your hand, \
    then if you added a Level 4 or lower monster by this effect, \
    you can Special Summon it in face-up Defense Position. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
Once per turn, during the End Phase of the turn this card was banished: \
    Shuffle this banished card into the Deck, \
    then you can add 1 banished non-Link {0} Dragon monster to your hand.\
"""

MESSIAH_BABY_PENDULUM_EFFECT = """\
You cannot Pendulum Summon monsters, except Dragon monsters. This effects cannot be negated. \
If you Pendulum Summon a monster(s): Add this card to your Extra Deck face-up.\
"""

MESSIAH_BABY_MONSTER_EFFECT = """\
1 non-Link Dragon monster
The Attribute of this card is also treated as {0} \
    while it is face-up on the field or in GY. \
    This effect cannot be negated. \
You can Tribute this Link Summoned card and discard 1 Dragon monster; \
    Special Summon from your {1}, \
    1 Dragon monster with the same Attribute as the discarded monster, \
    but it cannot attack directly this turn. \
During the Main Phase, except the turn this card was added to the Extra Deck face-up: \
    You can banish 1 Dragon monster from your hand or GY; \
    Place this face-up card from your Extra Deck in your Pendulum Zone. \
You can only use 1 "{CARD_NAME}" effect per turn, and only once that turn.\
"""
