[millennium-ascension]
id = 900000100
name = "Millennium Ascension"
type = "spell field"
effect = """\
When this card is activated: You can add 1 "Palladium" card from your Deck to your hand. \
"""
strings = ["Add 1 \"Palladium\" card to your hand?"]

[palladium-mahad]
id = 900000101
alias = 71703785
set = "palladium"
name = "Sacred Palladium Oracle Mahad"
type = "monster effect"
attribute = "light"
race = "spellcaster"
level = 7
atk = 2500
def = 2100
effect = """\
(This card's name is always treated as "Palladium Oracle Mahad".)
If this card is added to your hand: You can Special Summon it from your hand. \
You can reveal this card in your hand; add 1 Spell/Trap that mentions it, \
    from your Deck to your hand, then place 1 card from your hand on top of the Deck. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
If this card battles a DARK monster, its ATK is doubled during the Damage Step only. \
"""
strings = []

[palladium-mana]
id = 900000102
alias = 42006475
set = "palladium"
name = "Illusory Palladium Oracle Mana"
type = "monster effect"
attribute = "light"
race = "spellcaster"
level = 6
atk = 2000
def = 1700
effect = """\
(This card's name is always treated as "Palladium Oracle Mana".)
When a card or effect is activated that targets a Spellcaster monster(s) you control, \
    while this card is in your hand or GY (Quick Effect): You can Special Summon this card. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"Palladium" Spellcaster monsters and Level 7 or higher Spellcaster monsters you control cannot be destroyed by card effects. \
During damage calculation, if your other "Palladium" Spellcaster monster battles an opponent's monster (Quick Effect): \
    You can send this card from your hand or face-up field to the GY; \
    that monster you control gains ATK equal to this card's original ATK during that damage calculation only. \
"""
strings = ["Send this card to GY to up ATK"]

[palladium-seto]
id = 900000103
set = "palladium"
name = "Azure Palladium Oracle Seto"
type = "monster tuner effect"
attribute = "light"
race = "spellcaster"
level = 1
atk = 0
def = 0
effect = """\
You can reveal this card in your hand; \
    add from your Deck or GY to your hand, \
    1 Level 8 Dragon monster with 3000 or more ATK and 2500 or less DEF. \
    You cannot Normal Summon monsters the turn you activate this effect. \
You can discard this card, then target 1 "Blue-Eyes" monster you control; \
    Fusion Summon 1 Fusion Monster from your Extra Deck that lists that monster on the field as Fusion Material, \
    using it as the Fusion Material. \
You can Tribute this card; \
    Special Summon up to 3 copies of "Blue-Eyes White Dragon" from your hand, Deck or GY. \
    You cannot Special Summon other monsters the turn you activate this effect. \
You can only use 1 "{CARD_NAME}" effect per turn, and only once that turn.
"""
strings = [
    "Search a Dragon monster",
    "Affected by effect \"{CARD_NAME}\": cannot Normal Summon monsters",
    "Summon 3 \"Blue-Eyes White Dragon\"",
    "Affected by effect \"{CARD_NAME}\": cannot Special Summon monsters",
]

[palladium-shimon]
id = 900000104
set = "palladium"
name = "Palladium Wazir Shimon"
type = "monster effect"
attribute = "dark"
race = "spellcaster"
level = 5
atk = 1800
def = 2200
effect = """\
You can Special Summon this card (from your hand) by shuffling 5 monsters with different names in your GY into the Deck. \
If this card is Summoned: \
    You can add 1 "Forbidden One", "Exodia", or "Palladium" card from your Deck or GY to your hand, except "{CARD_NAME}". \
    You can only use this effect of "{CARD_NAME}" once per turn. \
If you would Tribute a monster(s) for a Tribute Summon an "Forbidden One", "Exodia", or "Palladium" monster, \
    you can Tribute a monster(s) your opponent controls, even though you do not control them. \
"""
strings = []

[palladium-hasan]
id = 900000105
set = "palladium"
name = "Palladium Protector Hasan"
type = "monster effect"
attribute = "dark"
race = "spellcaster"
level = 8
atk = 2300
def = 2800
effect = """\
When an opponent's monster declares a direct attack, if its ATK is greater than or equal to your LP: \
    You can Special Summon this card from your hand or GY, \
    and if you do, change the attack target to it and perform damage calculation. \
    You can only use this effect of "{CARD_NAME}" thrice per Duel. \
You take no battle damage from attacks involving this card. \
If this card leaves the field, return it to the bottom of the Deck. \
"""
strings = []

[palladium-shada]
id = 900000106
set = "palladium guardian"
name = "Palladium Guardian Shada"
type = "monster effect"
attribute = "light"
race = "warrior"
level = 4
atk = 1400
def = 1200
effect = """\
During damage calculation, if a monster battles another (Quick Effect): \
    You can Special Summon this card from your hand, \
    and if you do, "Palladium" monster you currently control cannot be destroyed by battle, until the end of this turn. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
At the end of the Damage Step, if this card battled an opponent's monster, \
    that monster lose 800 ATK. \
"""
strings = []

[palladium-karim]
id = 900000107
set = "palladium"
name = "Palladium Gardna Karim"
type = "monster effect"
attribute = "light"
race = "warrior"
level = 4
atk = 100
def = 2600
effect = """\
If this card is Normal or Flip Summoned, change it to Defense Position. \
    This effect cannot be negated. \
If this Defense Position card is attacked, it loses 800 DEF. \
You can only use 1 of these effects of "{CARD_NAME}" per turn, and only once that turn.
● When another "Palladium" monster you control is targeted for an attack: \
    You can change the attack target to this card, and perform damage calculation.
● When your opponent activates a card or effect \
    that targets this card or "Palladium" card you control (Quick Effect): \
    You can make this card loses exactly 800 DEF and that effect is negated.
"""
strings = ["Change attack target to this card"]

[palladium-isis]
id = 900000108
set = "palladium"
name = "Palladium Maiden Isis"
type = "monster effect"
attribute = "light"
race = "spellcaster"
level = 4
atk = 800
def = 2000
effect = """\
If this card is Summoned: \
    You can look at up to 5 cards from the top of your Deck, \
    then you can reveal 1 "Palladium" Spell/Trap or 1 Continuous Trap among them, and Set it, \
    it can be activated this turn, also place the remaining cards on top of your Deck in any order. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
If this card attacks a monster, before damage calculation: \
    You can change this card you control from face-up Attack Position to face-up Defense Position, \
    and if you do, return that monster to the hand, \
    also this card's battle position cannot be changed until the end of your next turn. \
"""
strings = ["Return battling monster to the hand"]

[palladium-gaia-knight]
id = 900000109
set = "palladium gaia-the-fierce-knight"
name = "Palladium Gaia the Fierce Knight"
type = "monster effect"
attribute = "light"
race = "warrior"
level = 7
atk = 2300
def = 2100
effect = """\
If you control no monsters, or your opponent controls a monster with 2000 or more ATK, \
    you can Special Summon this card (from your hand). \
    You can only Special Summon "{CARD_NAME}" once per turn this way. \
If this card attacks a monster, before damage calculation: \
    You can change the battle position of that monster. \
When you Ritual or Fusion Summon a "Palladium" monster, \
    you can banish this card from your GY as 1 of materials. \
"""
strings = ["Change battle position of battling monster"]
