[contact-space]
id = 900002100
alias = 42015635
name = "Contact Space"
type = "spell field"
effect = """\
(This card's name is always treated as "Neo Space".)
When this card is activated: You can add 1 LIGHT "Neos" monster from your Deck to your hand. \
If a Fusion Monster(s) you control that lists "Elemental HERO Neos" as material \
    is destroyed by battle, or leaves the field because of a card effect: \
    You can Special Summon 1 "Elemental HERO Neos" from your hand, Deck, Extra Deck, or GY, \
    ignoring its Summoning conditions and treated as Special Summoned properly. \
You can only use each above effects of "{CARD_NAME}" once per turn. \
Fusion Monsters that lists "Elemental HERO Neos" as material do not have to activate their effects during the End Phase \
    that shuffle them into the Extra Deck. \
Unaffected by other "Neos" cards' effects. \
    This effect cannot be negated. \
"""
strings = [
    "Add 1 \"Neos\" monster to your hand?",
    "Special Summon \"Elemental HERO Neos\"",
]

[elemental-hero-astrum-neos]
id = 900002101
alias = 89943723
name = "Elemental HERO Astrum Neos"
type = "monster fusion effect"
attribute = "light"
race = "warrior"
level = 7
atk = 2500
def = 2000
effect = """\
(This card's name is always treated as "Elemental HERO Neos".)
1 "HERO" monster + 1 Level 5 or lower monster
Must first be either Fusion Summoned, or Special Summoned by shuffling 1 Level 7 "Neos" monster you control into the Deck. \
If this card is Special Summoned from the Extra Deck: \
    You can Special Summon 1 "Neo-Spacian" monster from your hand, but it cannot attack this turn, \
    and if you do, this card gains ATK equal to that monster's ATK until the end of your opponent's turn, \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = []

[elemental-hero-neos-armiger]
id = 900002102
name = "Elemental HERO Neos Armiger"
set = "elemental-hero neos"
type = "monster effect"
attribute = "light"
race = "warrior"
level = 4
atk = 1900
def = 1300
effect = """\
While "Neo Space" is on the field, this card's name becomes "Elemental HERO Neos" while on the field or in the GY. \
    This effect cannot be negated. \
When this card is Normal or Special Summoned: \
    You can add 1 "Elemental HERO Neos" or 1 Spell/Trap that mentions it your Deck to your hand. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = []

[elemental-hero-divinity-neos]
id = 900002103
name = "Elemental HERO Divinity Neos"
set = "elemental-hero neos"
type = "monster fusion effect"
attribute = "divine"
race = "warrior"
level = 12
atk = 2500
def = 2500
effect = """\
1 Level 7 "Neos" monster + 4+ "Neo-Spacian" monsters with different Attributes
Must be Fusion Summoned with the above Fusion Materials. \
This card's Fusion Summon cannot be negated. \
Your opponent cannot Tribute this card, nor use it as material for an Summon, \
    also it cannot be returned to the Extra Deck. \
    This effect cannot be negated nor be copied. \
If this card is Fusion Summoned: \
    You can banish any number of Level 7 Fusion Monster that lists "Elemental HERO Neos" as material \
    from your GY and/or Extra Deck, up to the number of material used for its Summon, \
    and if you do, this card gains monster's effect and 500 original ATK/DEF for each banished monster. \
    Your opponent cannot activate cards or effects in response to this effect's activation. \
If this card is Fusion Summoned using 6 or more "Neo-Spacian" monsters, \
    it is unaffected by other cards' effect. \
"""
strings = ["Fusion Summoned using 6+ \"Neo-Spacian\" monster"]

[elemental-hero-abyss-neos]
id = 900002104
name = "Elemental HERO Abyss Neos"
set = "elemental-hero neos"
type = "monster fusion effect"
attribute = "dark"
race = "warrior"
level = 9
atk = 3000
def = 2500
effect = """\
"Elemental HERO Neos" + "Neo-Spacian Dark Panther" + "Neo-Spacian Aqua Dolphin"
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. \
    (You do not use "Polymerization".) \
If this card is Special Summoned from the Extra Deck: \
    Banish all cards in your opponent's Spell/Trap Zone or Monster Zone \
    (whichever has more, your choice, if tied). \
Once per turn, during the End Phase: \
    Shuffle this card into the Extra Deck, and if you do, \
    send all cards on the field to the GY. \
"""
strings = [
    "Banish all cards in your opponent's Spell/Trap Zone or Monster Zone",
    "Banish cards in Spell/Trap Zone",
    "Banish cards in Monster Zone",
]

[elemental-hero-steam-neos]
id = 900002105
name = "Elemental HERO Steam Neos"
set = "elemental-hero neos"
type = "monster fusion effect"
attribute = "water"
race = "warrior"
level = 9
atk = 3000
def = 2500
effect = """\
"Elemental HERO Neos" + "Neo-Spacian Aqua Dolphin" + "Neo-Spacian Flare Scarab"
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. \
    (You do not use "Polymerization".) \
Once per turn, when another card, or its effect, is activated (Quick Effect): \
    You can negate the activation, and if you do, destroy that card, \
    and if you do that, this card gain 400 ATK. \
Once per turn, during the End Phase: \
    Shuffle this card into the Extra Deck, and if you do, \
    neither player can declare an attack until the end of the next turn. \
"""
strings = [
    "Negate the activation and destroy & gain ATK",
    "Affected by effect \"{CARD_NAME}\": cannot declare an attack",
]

[elemental-hero-stratumine-neos]
id = 900002106
name = "Elemental HERO Stratumine Neos"
set = "elemental-hero neos"
type = "monster fusion effect"
attribute = "water"
race = "warrior"
level = 9
atk = 3000
def = 2500
effect = """\
"Elemental HERO Neos" + "Neo-Spacian Aqua Dolphin" + "Neo-Spacian Grand Mole"
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. \
    (You do not use "Polymerization".) \
Once per turn: You can shuffle into the Deck, \
    1 other card from either player's hand, field, or GY. \
    (The card in your opponent's hand is chosen at random). \
Once per turn, during the End Phase: \
    Shuffle this card into the Extra Deck, and if you do, \
    shuffle all banished cards into the Deck(s). \
"""
strings = [
    "Shuffle 1 card into the Deck",
    "Shuffle card on field, either GY, or your hand",
    "Shuffle random card in your opponent's hand",
]

[elemental-hero-hellfire-neos]
id = 900002107
name = "Elemental HERO Hellfire Neos"
set = "elemental-hero neos"
type = "monster fusion effect"
attribute = "fire"
race = "warrior"
level = 9
atk = 3000
def = 2500
effect = """\
"Elemental HERO Neos" + "Neo-Spacian Flare Scarab" + "Neo-Spacian Dark Panther"
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. \
    (You do not use "Polymerization".) \
If this card is Special Summoned from the Extra Deck: \
    destroy another cards on the field up to the number of Spells/Traps on the field, \
    and if you do, this card gains 400 ATK for each destroyed card. \
Once per turn, during the End Phase: \
    Shuffle this card into the Extra Deck, and if you do, \
    negate the effects of all face-up monsters on the field. \
"""
strings = []

[elemental-hero-nimbus-neos]
id = 900002108
name = "Elemental HERO Nimbus Neos"
set = "elemental-hero neos"
type = "monster fusion effect"
attribute = "light"
race = "warrior"
level = 9
atk = 3000
def = 2500
effect = """\
"Elemental HERO Neos" + "Neo-Spacian Glow Moss" + "Neo-Spacian Air Hummingbird"
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. \
    (You do not use "Polymerization".) \
If this card is Special Summoned from the Extra Deck: \
    You can banish 1 face-up monster on the field until the end of the next turn, \
    then gain LP equal to the original ATK of that monster. \
Once per turn, during the End Phase: \
    Shuffle this card into the Extra Deck, and if you do, \
    each player draws until they have 5 cards in their hand. \
"""
strings = []
