[cyberse-digital-dragon]
id = 900006001
set = "cyber"
name = "Cyberse Digital Dragon"
type = "monster xyz effect"
attribute = "dark"
race = "cyberse"
level = 4
atk = 2500
def = 2000
effect = """\
2 Level 4 monsters
While you control a Link Monster, \
    monsters your opponent controls cannot target monsters you control for attacks, except this one, \
    also your opponent cannot target monsters you control with card effects, except this one. \
Once per turn (Quick Effect): You can detach 1 material from this card, \
    then target 1 face-up monster on the field; \
    until the end of this turn, change its ATK to 0, also it cannot be destroyed by battle. \
At the end of the Damage Step, when this card attacks an opponent's monster, \
    but the opponent's monster was not destroyed by the battle: \
    You can send that monster to the GY. \
"""
strings = [
    "Make 1 monster ATK become 0 and cannot be destroyed by battle",
    "Send the battled monster to the GY",
]
