[the-seed-of-nightmare-paradise]
id = 900002000
name = "The Seed of Nightmare Paradise"
type = "spell field"
effect = """
You can only activate 1 "{CARD_NAME}" per turn. \
When this card is activated: Place from your hand or Deck underneath this card, 1 Field Spell that lists a "Yubel" card \
    or mentions "Uria, Lord of Searing Flames", "Hamon, Lord of Striking Thunder", or "Raviel, Lord of Phantasms", \
    except "{CARD_NAME}", and if you do, this effect becomes that card's effect when it is activated. \
Your opponent cannot target or destroy this card with card effects. \
This card gains the original effects of all Field Spells and Continuous Spell/Trap(s) underneath it. \
Once per turn, if you control a Level 10 or higher monster: \
    You can place from your hand or Deck underneath this card, \
    1 Field Spell or 1 Continuous Spell/Trap that lists a "Yubel" card \
    or mentions "Uria, Lord of Searing Flames", "Hamon, Lord of Striking Thunder", or "Raviel, Lord of Phantasms" \
    with a different name from the cards underneath this card. \
"""
strings = ["Attach 1 Continuous Spell/Trap in your GY"]

[raviel]
id = 900002001
alias = 69890967
rarity = "gold"
frame-path = "artwork/frame/raviel.png"
name = "Raviel, Ruler of Phantasm Demons"
type = "monster effect nomi"
attribute = "dark"
race = "fiend"
level = 10
atk = 4000
def = 4000
effect = """\
(This card's name is always treated as "Raviel, Lord of Phantasms".)
Cannot be Normal Summoned/Set. \
Must first be Special Summoned (from your hand) by Tributing 3 Fiend monsters. \
This card's Special Summon cannot be negated. \
Its control cannot switch. \
Cannot be Tributed, or used as material for an Summon by your opponent. \
Negate the effects of your opponent's monsters destroyed by battle with this card. \
The above effects cannot be negated. \
Each time your opponent Summons a monster(s), \
    Special Summon 1 "Phantasm Token" (Fiend/DARK/Level 1/ATK 1000/DEF 1000) in face-up Defense Position, \
    but it cannot declare an attack. \
Once per turn: You can Tribute up to 2 monsters; \
    this card gains ATK equal to the Tributed monsters' combined ATK had on the field, \
    until the end of this turn. \
"""
strings = [
    "Special Summon a \"Phantasm Token\"",
    "Tribute up to 2 monsters to gain ATK",
]

[uria]
id = 900002002
alias = 6007213
rarity = "gold"
frame-path = "artwork/frame/uria.png"
name = "Uria, Ruler of Searing Flames"
type = "monster effect nomi"
attribute = "fire"
race = "pyro"
level = 10
atk = 0
def = 0
effect = """\
(This card's name is always treated as "Uria, Lord of Searing Flames".)
Cannot be Normal Summoned/Set. \
Must first be Special Summoned (from your hand) by sending 3 face-up Traps you control to the GY. \
This card's Special Summon cannot be negated. \
Its control cannot switch. \
Cannot be Tributed, or used as material for an Summon by your opponent. \
Gains 1000 ATK/DEF for each Trap in your GY. \
The above effects cannot be negated. \
Once per turn: You can target 1 Set Spell/Trap your opponent controls; destroy it. \
    Neither player can activate Spell/Trap Cards in response to this effect's activation. \
During your Main Phase, except the turn this card was sent to the GY, \
    if this card is in the GY because it was destroyed in your Monster Zone by an opponent's card: \
    You can discard 1 Trap; Special Summon it from the GY. \
"""
strings = ["Destroy 1 Set Spell/Trap"]

[hamon]
id = 900002003
alias = 32491822
rarity = "gold"
frame-path = "artwork/frame/hamon.png"
name = "Hamon, Ruler of Striking Thunder"
type = "monster effect nomi"
attribute = "light"
race = "thunder"
level = 10
atk = 4000
def = 4000
effect = """\
(This card's name is always treated as "Hamon, Lord of Striking Thunder".)
Cannot be Normal Summoned/Set. \
Must first be Special Summoned (from your hand) by sending 3 face-up Continuous Spells you control to the GY. \
This card's Special Summon cannot be negated. \
Its control cannot switch. \
Cannot be Tributed, or used as material for an Summon by your opponent. \
While this card is in face-up Defense Position, \
    monsters your opponent controls cannot target monsters for attacks, except this one. \
The above effects cannot be negated. \
If this card destroys an opponent's monster by battle: \
    Inflict 1000 damage to your opponent. \
If this card on the field is destroyed, you take no damage this turn. \
"""
strings = [
    "Inflict 1000 damage to your opponent",
    "Affected by effect \"{CARD_NAME}\": you take no damage",
]

[armityle]
id = 900002004
alias = 43378048
rarity = "gold"
name = "Armityle, the Chaos Phantasm Emperor"
type = "monster fusion effect"
attribute = "dark"
race = "fiend"
level = 12
atk = 0
def = 0
effect = """\
(This card's name is always treated as "Armityle the Chaos Phantasm".)
"Uria, Lord of Searing Flames" + "Hamon, Lord of Striking Thunder" + "Raviel, Lord of Phantasms"
Must first be Special Summoned (from your Extra Deck) \
    by banishing the above cards you control. (You do not use "Polymerization".) \
This card's Special Summon cannot be negated. \
This card's battle position cannot be changed by card effects. \
Cannot be Tributed, or used as material for an Summon by your opponent. \
If this card's control was changed to your opponent, \
    its effects are negated, and also its control cannot switch. \
Once per turn, during the End Phase, if this card's control was changed this turn: \
    Banish all other cards you control, also shuffle it into the Extra Deck, \
    then the this card's owner can Special Summon 1 "Phantasm" Fusion Monster from the Extra Deck, \
    ignoring its Summoning conditions. (This is treated as a Fusion Summon.) \
The above effects cannot be negated. \
Cannot be destroyed by battle. \
This card's original ATK becomes 10,000 during your turn only. \
Once per turn: You can give control of this card to your opponent. \
"""
strings = [
    "Cannot switch control",
    "Special Summon 1 \"Phantasm\" Fusion Monster?",
    "Give control to your opponent",
]
