[the-eye-of-nightmare]
id = 900002000
alias = 13301895
name = "The Eye of Nightmare"
type = "spell field"
effect = """
(This card's name is always treated as "Fallen Paradise".)
You can only activate 1 "{CARD_NAME}" per turn. \
When this card is activated: You can add 1 card that mentions \
    "Uria, Lord of Searing Flames", "Hamon, Lord of Striking Thunder", or "Raviel, Lord of Phantasms", \
    from your Deck to your hand. \
Your opponent cannot banish, target \
    "Uria, Lord of Searing Flames", "Hamon, Lord of Striking Thunder", "Raviel, Lord of Phantasms", \
    or "Armityle the Chaos Phantasm" in your Monster Zones with card effects, \
    those monsters cannot be destroyed by your opponent's card effects while you control them. \
This card gains these effects based on the number of \
    "Uria, Lord of Searing Flames", "Hamon, Lord of Striking Thunder", "Raviel, Lord of Phantasms", \
    and/or "Armityle the Chaos Phantasm" with different names you control.
● 1+: Your opponent cannot banish, target or destroy this card with card effects, \
    also the activation and effect of this card's effects cannot be negated. \
    Once per turn: You can draw 2 cards.
● 2+: You can activate a Continuous Trap from your hand or the turn it was Set. \
    You can only use this effect of "{CARD_NAME}" once per turn.
● 3+: Once per turn: You can target 1 face-up Continuous Spell/Trap that mentions \
    "Uria, Lord of Searing Flames", "Hamon, Lord of Striking Thunder", or "Raviel, Lord of Phantasms" \
    with a different name from the cards attached to this card, except "{CARD_NAME}" \
    that you control or is in your GY; \
    attach it to this card and if you do this card gains that card's effects.
"""
strings = [
    "Add card that mentions Sacred Beast?",
    "Draw 2 card",
    "Attach 1 Continuous Spell/Trap to this card",
]

[uria]
id = 900002001
alias = 6007213
rarity = "gold"
frame-path = "frame/uria.png"
name = "Uria, Ruler of Searing Flames"
type = "monster effect"
attribute = "fire"
race = "pyro"
level = 10
atk = 0
def = 0
effect = """\
(This card's name is always treated as "Uria, Lord of Searing Flames".)
Cannot be Normal Summoned/Set. \
Must first be Special Summoned (from your hand) by sending 3 face-up Traps you control to the GY. \
This card's Special Summon cannot be negated. \
Control of it cannot switch. \
Cannot be Tributed, or used as material for an Summon by your opponent. \
Gains 1000 ATK/DEF for each Trap in your GY. \
The above effects cannot be negated. \
Once per turn: You can target 1 Set Spell/Trap your opponent controls; destroy it. \
    Neither player can activate Spell/Trap Cards in response to this effect's activation. \
During your Main Phase, except the turn this card was sent to the GY, \
    if this card is in the GY because it was destroyed in your Monster Zone by an opponent's card: \
    You can discard 1 Trap; Special Summon it from the GY. \
"""
strings = ["Destroy 1 Set Spell/Trap"]

[hamon]
id = 900002002
alias = 32491822
rarity = "gold"
frame-path = "frame/hamon.png"
name = "Hamon, Ruler of Striking Thunder"
type = "monster effect"
attribute = "light"
race = "thunder"
level = 10
atk = 4000
def = 4000
effect = """\
(This card's name is always treated as "Hamon, Lord of Striking Thunder".)
Cannot be Normal Summoned/Set. \
Must first be Special Summoned (from your hand) by sending 3 face-up Continuous Spells you control to the GY. \
This card's Special Summon cannot be negated. \
Control of it cannot switch. \
Cannot be Tributed, or used as material for an Summon by your opponent. \
While this card is in face-up Defense Position, \
    monsters your opponent controls cannot target monsters for attacks, except this one. \
The above effects cannot be negated. \
If this card destroys an opponent's monster by battle: \
    Inflict 1000 damage to your opponent. \
If this card on the field is destroyed, you take no damage this turn. \
"""
strings = [
    "Inflict 1000 damage to your opponent",
    "Affected by effect \"{CARD_NAME}\": you take no damage",
]

[raviel]
id = 900002003
alias = 69890967
rarity = "gold"
frame-path = "frame/raviel.png"
name = "Raviel, Ruler of Phantasm Demons"
type = "monster effect"
attribute = "dark"
race = "fiend"
level = 10
atk = 4000
def = 4000
effect = """\
(This card's name is always treated as "Raviel, Lord of Phantasms".)
Cannot be Normal Summoned/Set. \
Must first be Special Summoned (from your hand) by Tributing 3 Fiend monsters. \
This card's Special Summon cannot be negated. \
Control of it cannot switch. \
Cannot be Tributed, or used as material for an Summon by your opponent. \
Negate the effects of your opponent's monsters destroyed by battle with this card. \
The above effects cannot be negated. \
Each time your opponent Summons a monster(s), \
    Special Summon 1 "Phantasm Token" (Fiend/DARK/Level 1/ATK 1000/DEF 1000) in face-up Defense Position, \
    but it cannot declare an attack. \
Once per turn: You can Tribute up to 2 monsters; \
    this card gains ATK equal to the Tributed monsters' combined ATK had on the field, \
    until the end of this turn. \
"""
strings = [
    "Special Summon a \"Phantasm Token\"",
    "Tribute up to 2 monsters to gain ATK",
]

[armityle]
id = 900002004
alias = 43378048
rarity = "gold"
name = "Armityle, the Chaos Phantasm Emperor"
type = "monster fusion effect"
attribute = "dark"
race = "fiend"
level = 12
atk = 0
def = 0
effect = """\
(This card's name is always treated as "Armityle the Chaos Phantasm".)
"Uria, Lord of Searing Flames" + "Hamon, Lord of Striking Thunder" + "Raviel, Lord of Phantasms"
Must first be Special Summoned (from your Extra Deck) \
    by banishing the above cards you control. (You do not use "Polymerization".) \
This card's Special Summon cannot be negated. \
This card's battle position cannot be changed by card effects. \
Cannot be Tributed, or used as material for an Summon by your opponent. \
If this card's control was changed to your opponent, \
    its effects are negated, also control of it cannot switch. \
Once per turn, during the End Phase, if this card's control was changed this turn: \
    Banish all other cards you control, also shuffle it into the Extra Deck, \
    then the owner of this card can Special Summon it from their Extra Deck, \
    ignoring its Summoning conditions. (This is treated as a Fusion Summon.) \
The above effects cannot be negated. \
Cannot be destroyed by battle. \
Gains 10,000 ATK during your turn only. \
Once per turn: You can give control of this card to your opponent. \
"""
strings = [
    "Cannot switch control",
    "Special Summon it?",
    "Give control to your opponent",
]

[successor-of-phantasmal-lord]
id = 900002005
set = "phantasm"
name = "Successor of Phantasmal Lord"
type = "monster fusion effect"
attribute = "dark"
race = "fiend"
level = 10
atk = 0
def = 0
effect = """\
"Uria, Lord of Searing Flames", "Hamon, Lord of Striking Thunder", or "Raviel, Lord of Phantasms" + 1 Effect Monster
Must first be Special Summoned (from your Extra Deck) by banishing the above cards you control. \
    (You do not use "Polymerization".) \
Cannot be destroyed by battle.
This card gains these effects, depending on the materials used to Summon this card.
● "Uria, Lord of Searing Flames": Unaffected by your opponent's Trap effects, also this card gains 1000 ATK for each Continuous Trap in your GY during your turn only.
● "Hamon, Lord of Striking Thunder": Unaffected by your opponent's Spell effects, also this card gains 4000 ATK during your turn only.
● "Raviel, Lord of Phantasms": Gains 4000 ATK during your turn only, also if this card attacks a Defense Position monster, inflict piercing battle damage.
"""
strings = [
    "Summoned with \"Uria, Lord of Searing Flames\"",
    "Summoned with \"Hamon, Lord of Striking Thunder\"",
    "Summoned with \"Raviel, Lord of Phantasms\"",
]

[yubel-desperate-incarnate]
id = 900002006
alias = 4779091
name = "Yubel - Desperate Incarnate"
type = "monster effect"
attribute = "dark"
race = "fiend"
level = 11
atk = 0
def = 0
effect = """\
(This card's name is always treated as "Yubel - Terror Incarnate".)
Cannot be Normal Summoned/Set. \
Must be Special Summoned by "Yubel". \
You can discard this card; add 1 "Yubel", or 1 card that mentions it, \
    from your Deck to your hand, except "{CARD_NAME}". \
    You can only use this effect of "{CARD_NAME}" once per turn. \
Cannot be destroyed by battle, also you take no damage from battles involving this card. \
At the end of the Damage Step, if this face-up Attack Position card battles an opponent's monster: \
    Inflict damage to your opponent equal to that monster's ATK, also destroy 1 other card on the field. \
If this face-up card leaves the field: \
    You can Special Summon 1 "Yubel - The Ultimate Nightmare", \
    or 1 Fusion Monster that mentions it as material, \
    from your hand, Deck, GY or Extra Deck. ignoring its Summoning conditions. \
    (This is treated as a Fusion Summon, if able.) \
"""
strings = ["Inflict damage & destroy 1 card on the field"]

[yubel-the-ultimate-phantasmal-nightmare]
id = 900002007
rarity = "gold"
set = "phantasm"
name = "Yubel - The Ultimate Phantasmal Nightmare"
type = "monster fusion effect"
attribute = "dark"
race = "fiend"
level = 12
atk = 0
def = 0
effect = """\
"Yubel - The Ultimate Nightmare" + 1 "Phantasm" Fusion Monster
Must be Fusion Summoned with the above Fusion Materials. \
Control of it cannot switch. \
This card's name is also treated as "Armityle the Chaos Phantasm" while it is on the field. \
This card's battle position cannot be changed by card effects. \
Cannot be Tributed, or used as material for an Summon by your opponent. \
Cannot be destroyed by battle. \
The above effects cannot be negated. \
Your opponent takes any battle damage you would have taken from battles involving this card. \
At the end of the Damage Step, if this face-up Attack Position card battles an opponent's monster: \
    Inflict damage to your opponent equal to that monster's ATK, also destroy that monster. \
Once per turn (Quick Effect): \
    You can banish 1 face-up monster your opponent controls, and if you do, \
    Special Summon 1 "Phantasmal Nightmare Token" (Fiend/DARK/Level 12/ATK ?/DEF 0). \
    The Token's ATK/DEF become the original ATK/DEF of that monster, \
    also you take no damage from battles involving it. \
"""
strings = [
    "Inflict damage & destroy battling monster",
    "Banish 1 face-up monster & create token",
]

[phantasmal-nightmare-token]
id = 900002008
set = "phantasm"
name = "Phantasmal Nightmare Token"
type = "monster token"
attribute = "dark"
race = "fiend"
level = 12
atk = "?"
def = 0
effect = """\
Special Summoned with the effect of "Yubel - The Ultimate Phantasmal Nightmare". \
This Token's ATK/DEF become the original ATK/DEF of the banished monster, \
    also you take no damage from battles involving it. \
"""
strings = []

[seed-of-desolation]
id = 900002009
name = "Seed of Desolation"
type = "monster effect"
attribute = "dark"
race = "plant"
level = 1
atk = 0
def = 0
effect = """\
You can reveal this card in your hand, then target 1 face-up monster you control; \
    Destroy it, and if you do, Special Summon this card from your hand or 1 "Yubel" from your hand or Deck. \
(Quick Effect): You can banish this card from your GY, then target 1 Fiend monster you control; \
    Destroy it, and if you do, you can draw 1 card. \
You can only use each effect of "{CARD_NAME}" once per turn.
"""
strings = [
    "Special Summon this card",
    "Special Summon \"Yubel\"",
    "Draw 1 card?",
]

[opening-of-the-spirit-gates]
id = 80312545
card-limit = "ocg tcg"
name = "Opening of the Spirit Gates"
type = "spell continuous"
effect = """
When this card is activated: Add 1 "Uria, Lord of Searing Flames", "Hamon, Lord of Striking Thunder", \
    or "Raviel, Lord of Phantasms", OR 1 monster that specifically lists any of those cards in its text, \
    from your Deck to your hand. \
Once per turn: You can discard 1 card; \
    Special Summon 1 Fiend monster with 0 ATK/DEF from your GY. \
Once per turn, if you control a Level 10 monster: \
    You can add 1 Continuous Spell from your GY to your hand. \
You can only activate 1 "Opening of the Spirit Gates" per turn. \
"""
generate-pic = false
generate-script = false
strings = [
    "Search card",
    "Special Summon Fiend monster with 0 ATK/DEF",
    "Return 1 Continuous Spell",
]

[awakening-of-the-sacred-beasts]
id = 53701259
card-limit = "ocg tcg"
name = "Awakening of the Sacred Beasts"
type = "trap continuous"
effect = """
This card gains these effects based on the number of \
    "Uria, Lord of Searing Flames", "Hamon, Lord of Striking Thunder", and/or "Raviel, Lord of Phantasms" \
    with different names you control.
● 1+: Each time your opponent Normal or Special Summons a monster(s): \
    Gain LP equal to the ATK of that monster(s).
● 2+: Negate the activated effects of monsters your opponent controls.
● 3: Any monsters sent to your opponent's GY are banished instead.
Once per your turn, if you control a Level 10 monster: \
    You can add 1 Continuous Trap from your GY to your hand. \
"""
generate-pic = false
generate-script = false
strings = ["Return 1 Continuous Trap"]

[hyper-blaze]
id = 16317140
card-limit = "ocg tcg"
name = "Hyper Blaze"
type = "trap continuous"
effect = """
To Special Summon "Uria, Lord of Searing Flames" using its own procedure, \
    you can also use face-down Traps you control. \
Once per battle, when an attack is declared involving your "Uria, Lord of Searing Flames": \
    You can send 1 Trap from your hand or Deck to the GY; \
    its ATK/DEF become the number of face-up Traps on the field and in the GYs x 1000, \
    for the rest of this turn. \
Once per turn: You can discard 1 card; \
    add to your hand or Special Summon, \
    1 "Uria, Lord of Searing Flames", "Hamon, Lord of Striking Thunder", or "Raviel, Lord of Phantasms" \
    from your GY, ignoring its Summoning conditions. \
"""
generate-pic = false
generate-script = false
strings = [
    "Send Trap to gain ATK",
    "Return or Special Summon 1 Sacred Beast",
    "Select a Sacred Beast",
    "Special Summon it",
]
