[supreme-king-dark-castle]
id = 900002200
set = "supreme-king"
name = "Supreme King's Dark Castle"
type = "spell field"
effect = """
You can only activate 1 "{CARD_NAME}" per turn. \
When this card is activated: Add 1 "Polymerization" Spell Card or "Fusion" Spell Card from your Deck to your hand. \
You can Fusion Summon Fusion Monsters that must be Special Summoned with "Dark Fusion", \
    with effects other than "Dark Fusion". \
The activation of your cards and effects that include an effect that Fusion Summons a Fusion Monster cannot be negated, \
    also your opponent's cards and effects cannot activate when a monster is Fusion Summoned this way. \
"""
strings = ["Add 1 Fusion Spell?"]

[supreme-king-hero]
id = 900002201
rarity = "gold"
set = "supreme-king hero"
name = "The Supreme King HERO"
type = "monster fusion effect"
attribute = "dark"
race = "warrior"
level = 10
atk = "?"
def = "?"
effect = """\
1 "HERO" monster + 1+ Effect Monsters on the field
Must be Special Summoned with "Super Polymerization".
"""
strings = []

[evil-hero-cosmos]
id = 900002202
set = "evil-hero"
name = "Evil HERO Cosmos"
type = "monster effect"
attribute = "dark"
race = "fiend"
level = 7
atk = 2500
def = 2000
effect = """\
You can Special Summon this card (from your hand or GY) \
    by shuffling 1 "HERO" Fusion or Link Monster you control into the Extra Deck. \
    You can only Special Summon "{CARD_NAME}" once per turn this way. \
If this card attacks, during damage calculation: \
    You can Tribute 1 face-up "HERO" monster; \
    this card gains ATK equal to the Tributed monster's ATK, until the End Phase. \
During your Main Phase or your opponent's turn (Quick Effect): \
    You can shuffle into the Deck, this card you control and 1 other "HERO" monster you control or in your hand, \
    and if you do, Special Summon 1 Fusion monster from your Extra Deck, \
    that mentions the other Tributed monster as material \
    and must be Special Summoned with "Dark Fusion". \
    (This is treated as a Fusion Summon with "Dark Fusion".) \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = [
    "Tribute 1 \"HERO\" to gain ATK",
    "Special Summon 1 \"Evil HERO\" Fusion monster from Extra Deck",
]

[evil-hero-aero-scout]
id = 900002203
set = "evil-hero"
name = "Evil HERO Aero Scout"
type = "monster effect"
attribute = "wind"
race = "fiend"
level = 3
atk = 1000
def = 1000
effect = """\
(This card's name is also treated as "Elemental HERO Avian".)
If this card is in your hand: \
    You can send 1 "Evil HERO" monster from your Deck to the GY, except "{CARD_NAME}", \
    and if you do, Special Summon this card from your hand. \
    You cannot Special Summon monsters from the Extra Deck, except "HERO" monsters, the turn you activate this effect. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
If this card is used as material for a Fusion Summon, and sent to the GY or banished: \
    You can switch the original ATK/DEF of all monsters your opponent currently controls. \
"""
strings = [
    "Affected by effect \"{CARD_NAME}\": cannot Special Summon from the Extra Deck, except \"HERO\" monsters",
]

[evil-hero-blaster-minx]
id = 900002204
set = "evil-hero"
name = "Evil HERO Blaster Minx"
type = "monster effect"
attribute = "fire"
race = "fiend"
level = 3
atk = 1200
def = 800
effect = """\
(This card's name is also treated as "Elemental HERO Burstinatrix".)
You can send 1 "Evil HERO" monster from your hand or Deck to the GY, except "{CARD_NAME}", and if you do, \
    this card's Attribute, Level and ATK/DEF become the same as that monster, until the end of next turn. \
    You cannot Special Summon monsters from the Extra Deck, except "HERO" monsters, the turn you activate this effect. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
If this card is used as material for a Fusion Summon, and sent to the GY or banished: \
    You can make 1 Fiend monster you control gains 1000 ATK. \
"""
strings = [
    "Send 1 \"Evil HERO\" to the GY to copy its Attribute, Level, ATK/DEF",
    "Affected by effect \"{CARD_NAME}\": cannot Special Summon from the Extra Deck, except \"HERO\" monsters",
]

[evil-hero-igneous-insurgent]
id = 900002205
set = "evil-hero"
name = "Evil HERO Igneous Insurgent"
type = "monster effect"
attribute = "earth"
race = "fiend"
level = 4
atk = 800
def = 2000
effect = """\
(This card's name is also treated as "Elemental HERO Clayman".)
You can Special Summon this card (from your hand) by discarding 1 \"Evil HERO\" monster. \
Once per turn, when your monster is targeted for an attack: You can negate the attack. \
If this card is used as material for a Fusion Summon, and sent to the GY or banished: \
    You can inflict damage to your opponent equal to original Level of 1 Fiend monster you control x 200. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = ["Negate the attack"]

[evil-hero-bubbling-anger]
id = 900002206
set = "evil-hero"
name = "Evil HERO Bubbling Anger"
type = "monster effect"
attribute = "water"
race = "fiend"
level = 4
atk = 800
def = 1200
effect = """\
(This card's name is also treated as "Elemental HERO Bubbleman".)
If you control a "Evil HERO" monster, you can Special Summon this card (from your hand). \
You take no damage from battles involving this card, \
    also destroy an opponent's monster that battles this card at the end of the Damage Step. \
If this card is used as material for a Fusion Summon, and sent to the GY or banished: \
    You can draw 2 cards, then discard 1 card. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = ["Destroy the battled monster"]

[evil-hero-black-bolt]
id = 900002207
set = "evil-hero"
name = "Evil HERO Black Bolt"
type = "monster effect"
attribute = "light"
race = "fiend"
level = 4
atk = 1600
def = 1400
effect = """\
(This card's name is also treated as "Elemental HERO Sparkman".)
You can target 1 face-up monster on the field; change its battle position. \
You can banish this card from your GY, \
    then target 1 your banished "Evil HERO" monster, except "{CARD_NAME}"; \
    either add it to your hand or Special Summon it. \
If this card is used as material for a Fusion Summon, and sent to the GY or banished: \
    You can destroy 1 monster your opponent controls. \
You can only use each effect of "{CARD_NAME}" once per turn. \
"""
strings = ["Change position of 1 face-up monster"]

[evil-hero-savage-heart]
id = 900002208
set = "evil-hero"
name = "Evil HERO Savage Heart"
type = "monster effect"
attribute = "earth"
race = "fiend"
level = 4
atk = 1500
def = 1600
effect = """\
(This card's name is also treated as "Elemental HERO Wildheart".)
If this card is Normal or Special Summoned: \
    You can Special Summon 1 "Evil HERO" monster from your hand. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
Unaffected by your opponent's Trap effects. \
If this card is used as material for a Fusion Summon, and sent to the GY or banished: \
    You can negate all your opponent's Trap effects on the field this turn. \
"""
strings = []

[evil-hero-revenge-smog]
id = 900002209
set = "evil-hero"
name = "Evil HERO Revenge Smog"
type = "monster effect"
attribute = "dark"
race = "fiend"
level = 4
atk = 1800
def = 300
effect = """\
If this card is Normal or Special Summoned: You can activate 1 of these effects.
● Inflict 300 damage to your opponent for each "Evil HERO" monster in your GY.
● Target 1 "Evil HERO" monster in your GY; add it to your hand or Special Summon it.
(Quick Effect): You can banish this card from your field or GY; \
    activate 1 "Supreme King" Field Spell directly from your hand, Deck or GY. \
You can only use each effect of "{CARD_NAME}" once per turn. \
"""
strings = [
    "Inflict damage or Special summon",
    "Inflict 300 damage to your opponent for each \"Evil HERO\"",
    "Return or Special Summon 1 \"Evil HERO\" in GY",
    "Activate Field Spell that mentions \"Dark Fusion\"",
]

[evil-hero-cursed-shadow]
id = 900002210
set = "evil-hero"
name = "Evil HERO Cursed Shadow"
type = "monster effect"
attribute = "dark"
race = "fiend"
level = 4
atk = 1300
def = 1500
effect = """\
If this card is Normal Summoned: You can declare 1 Monster Type, \
    then Special Summon 1 "Evil Token" (Fiend/DARK/Level 7/ATK 2500/DEF 2500) in Defense Position. \
    The Token's Type become the declared Type when it is Summoned. \
    You cannot Special Summon monsters from the Extra Deck, except "HERO" monsters, the turn you activate this effect. \
If this card is sent to the GY, or banished: \
    You can add 1 "Evil HERO" monster from your Deck to your hand, except "{CARD_NAME}". \
You can only use each effect of "{CARD_NAME}" once per turn. \
"""
strings = [
    "Affected by effect \"{CARD_NAME}\": cannot Special Summon from the Extra Deck, except \"HERO\" monsters",
]

[evil-hero-infernal-executor]
id = 900002211
set = "evil-hero"
name = "Evil HERO Infernal Executor"
type = "monster effect"
attribute = "dark"
race = "fiend"
level = 4
atk = 1700
def = 1100
effect = """\
If this card is in your hand or GY: \
    You can banish 1 "Evil HERO" monster from your field or GY, except "{CARD_NAME}", \
    and if you do, Special Summon this card. \
If this card is Special Summoned: \
    You can send 1 "Evil HERO" monster from your hand or Deck to the GY, except "{CARD_NAME}"; \
    this card's name becomes the sent monster's name and gains ATK equal to the Level of that monster x 100. \
    also your opponent sends cards from the top of their Deck to the GY equal to the Level of that monster. \
You can only use each effect of "{CARD_NAME}" once per turn. \
"""
strings = []

[evil-hero-infernal-scepter]
id = 900002212
set = "evil-hero"
name = "Evil HERO Infernal Scepter"
type = "monster effect"
attribute = "dark"
race = "fiend"
level = 3
atk = 800
def = 1200
effect = """\
(Quick Effect): You can discard this card, then target 1 "Evil HERO" monster on the field; \
    it gains ATK equal to its Level x 200 until the end of this turn. \
If this card is sent to the GY, or banished: \
    You can target 1 "Dark Fusion", or 1 card that mentions it, \
    in your GY, except "{CARD_NAME}"; \
    add it to your hand. \
You can only use 1 "{CARD_NAME}" effect per turn, and only once that turn. \
"""
strings = []
