[red-eyes-black-feral-dragon]
id = 900001201
alias = 74677422
name = "Red-Eyes Black Feral Dragon"
set = "red-eyes"
type = "monster effect"
attribute = "dark"
race = "dragon"
level = 7
atk = 2400
def = 2000
effect = """\
(This card's name is always treated as Red-Eyes Black Dragon".)
This card is treated as a Normal Monster while in the hand, GY, or on the field. \
    This effect cannot be negated. \
If this card is sent from the hand or Deck to the GY: You can Special Summon this card. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
Once per turn, during the End Phase, if this card attacked a monster this turn: \
    You can inflict damage to your opponent equal to this card's original ATK. \
"""
strings = ["Inflict damage equal to this card's original ATK"]

[red-eyes-extreme-dragon]
id = 900001202
name = "Red-Eyes Extreme Dragon"
set = "red-eyes"
type = "monster fusion effect"
attribute = "dark"
race = "dragon"
level = 11
atk = 3600
def = 3000
effect = """\
3 Level 7 "Red-Eyes" monsters
A Fusion Summon of this card can only be done with the above materials. \
If this card is Fusion Summoned: \
    You can add up to 3 "Red-Eyes" Trap with different names from your Deck and/or GY to your hand. \
    If this card was Fusion Summoned using "Red-Eyes Black Dragon" as material, you can also add Equip Spells. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
Your opponent cannot target face-up Spells/Traps you control with card effects, \
    also they cannot be destroyed by your opponent's card effects. \
Once per turn: You can target 1 "Red-Eyes" monster \
    that in your GY or banishment, except "{CARD_NAME}"; shuffle it into the Deck, \
    and if you do, if you control this face-up Fusion Summoned card, \
    inflict damage to your opponent equal to its original ATK. \
"""
strings = ["Shuffle 1 \"Red-Eyes\" monster into the Deck"]

[archfiend-darkness-skull-dragon]
id = 900001203
name = "Archfiend Darkness Skull Dragon"
set = "archfiend"
type = "monster fusion effect"
attribute = "dark"
race = "dragon"
level = 10
atk = 3600
def = 2800
effect = """\
1 "Red-Eyes" Dragon monster + 1 Level 8 or higher DARK Dragon Fusion monster
This Fusion Summoned card unaffected by other monsters' effects. \
If this card is Fusion Summoned: Destroy all monsters your opponent controls, and if you do, \
    inflict damage to your opponent equal to the highest original ATK among those destroyed monsters (your choice, if tied). \
During the End Phase, if this card is Fusion Summoned using an Normal Monster: \
    inflict 200 damage to your opponent for each card on the field. \
You can only use each effect of "{CARD_NAME}" once per turn. \
"""
strings = [
    "Fusion Summoned using an Normal Monster",
    "Inflict 200 damage to your opponent for each card on the field",
]

[red-eyes-blaster-dragon]
id = 900001204
name = "Red-Eyes Blaster Dragon"
set = "red-eyes"
type = "monster fusion effect"
attribute = "dark"
race = "dragon"
level = 7
atk = 2800
def = 2400
effect = """\
"Red-Eyes Black Dragon" + 1 Gemini Monster
At the start of the Damage Step, if this card battles an opponent's monster: \
    You can destroy that opponent's monster. \
If this card destroys a monster by battle or by its own effect: It gains 500 ATK, \
    then if its ATK becomes 4000 or higher, destroy it. \
If this card is destroyed by battle or card effect: \
    You can Special Summon 1 "Red-Eyes Black Dragon" from your hand, Deck, or GY. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = ["Destroy the battling monster", "Gain 1000 ATK"]

[red-eyes-dark-steel-dragon]
id = 900001205
name = "Red-Eyes Dark Steel Dragon"
set = "red-eyes"
type = "monster xyz effect"
attribute = "dark"
race = "dragon"
level = 10
atk = 2800
def = 2400
effect = """\
2 Level 10 monsters with same Type and Attribute
You can also Xyz Summon this card by using 1 Level 9 or higher "Red-Eyes" monster you control as material. \
If this card would be destroyed by battle or card effect, you can detach 1 material from this card instead. \
During your Main Phase: You can Special Summon 1 Dragon monster or "Red-Eyes" monster, except "{CARD_NAME}", \
    that from your hand, GY, or banishment. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
If this card has an "Red-Eyes" monster as material, it gains these effects.
● Gains 400 ATK for each Dragon monster in your GY.
● When your opponent activates a Spell Card (Quick Effect): \
    You can discard 1 card; negate the activation, and if you do, destroy it.
"""
strings = [
    "Xyz Summon by using a Level 10 \"Red-Eyes\" monster",
    "Special Summon 1 \"Red-Eyes\" monster or Dragon monster",
    "Discard to negate the activation",
]

[red-eyes-darkness-flare-metal-dragon]
id = 900001206
name = "Red-Eyes Darkness Flare Metal Dragon"
set = "red-eyes"
type = "monster xyz effect"
attribute = "dark"
race = "dragon"
level = 8
atk = 2800
def = 2400
effect = """\
3 Level 8 DARK monsters
You can also Xyz Summon this card by using a Rank 7 "Red-Eyes" Xyz Monster you control as material. \
    (Transfer its materials to this card.) \
This Xyz Summoned card cannot be destroyed by card effects. \
Once per turn (Quick Effect): You can Special Summon 1 Normal Monster from your hand or GY. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
If this card has "Red-Eyes Flare Metal Dragon" as material, it gains these effects.
● Gains 300 ATK for each material attached to it.
● Once per turn, when your opponent activates a card or effect (Quick Effect): \
    You can detach 1 material from this card; \
    negate the activation, and if you do, destroy it.
● If this card destroys a card(s) by battle or by its own effect: \
    Attach the destroyed card(s) to it.
"""
strings = [
    "Xyz Summon by using a Rank 7 \"Red-Eyes\" Xyz Monster",
    "Special Summon 1 Normal Monster in your GY",
    "Negate the activation & destroy",
]

[meteor-flare-fusion]
id = 900001208
alias = 6172122
name = "Meteor Flare Fusion"
type = "spell"
effect = """\
(This card's name is always treated as "Red-Eyes Fusion".)
Fusion Summon 1 Fusion Monster from your Extra Deck,\
    by shuffling the materials from your hand, field, and/or GY into the Deck, \
    including a "Red-Eyes" monster that it lists as material, \
    and if you do, its name becomes "Red-Eyes Black Dragon". \
You can only activate 1 "{CARD_NAME}" per turn. \
"""
strings = []

[red-eyes-metalmorph]
id = 900001209
name = "Red-Eyes Metalmorph"
set = "red-eyes"
type = "trap"
effect = """\
Target 1 "Red-Eyes" monster you control; equip this card to it. \
It cannot be targeted by an opponent's card effects. \
If it attacks, it gains ATK equal to half the ATK of the attack target, during damage calculation only. \
You can send this Equip Card to the GY; \
    Set 1 "Red-Eyes" Trap directly from your Deck or GY, except "{CARD_NAME}". \
    It can be activated this turn. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = [
    "Send this card to GY & Set 1 \"Red-Eyes\" Trap directly from your Deck or GY",
]
