[red-eyes-black-inferno-dragon]
id = 900001201
alias = 74677422
name = "Red-Eyes Black Inferno Dragon"
set = "red-eyes"
type = "monster effect"
attribute = "dark"
race = "dragon"
level = 7
atk = 2400
def = 2000
effect = """\
(This card's name is always treated as Red-Eyes Black Dragon".)
This card is treated as a Normal Monster while in the hand or GY. \
    This effect cannot be negated. \
If this card is sent from the hand or Deck to the GY: You can Special Summon this card. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
Once per turn, if damage calculation is performed involving this card, at the end of the Battle Phase: \
    You can inflict damage to your opponent equal to this card's original ATK. \
"""
strings = ["Inflict damage equal to this card's original ATK"]

[red-eyes-extreme-dragon]
id = 900001202
name = "Red-Eyes Extreme Dragon"
set = "red-eyes"
type = "monster fusion effect"
attribute = "dark"
race = "dragon"
level = 11
atk = 3600
def = 3000
effect = """\
3 "Red-Eyes" Dragon monsters
A Fusion Summon of this card can only be done with the above materials. \
If this card is Fusion Summoned: \
    You can add up to 3 "Red-Eyes" Trap with different names from your Deck and/or GY to your hand. \
    If this card was Fusion Summoned using "Red-Eyes Black Dragon" as material, you can also add Equip Spells. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
Your opponent cannot target face-up Spells/Traps you control with card effects, \
    also they cannot be destroyed by your opponent's card effects. \
Once per turn: You can target 1 Level 7 or lower "Red-Eyes" monster \
    that is banished or in your GY, except "{CARD_NAME}"; shuffle it into the Deck, \
    and if you do, if you control this face-up Fusion Summoned card, \
    inflict damage to your opponent equal to its original ATK. \
"""
strings = ["Shuffle 1 \"Red-Eyes\" monster into the Deck"]
