[numeron-genesis-dragon]
id = 900004001
rarity = "gold"
name = "Numeron Genesis Dragon"
set = "numeron"
type = "monster xyz effect"
attribute = "divine"
race = "dragon"
rank = 13
atk = 0
def = 0
effect = """\
Cannot be Xyz Summoned. \
Must be Special Summoned (from your Extra Deck) by overlaying all Xyz Monsters you control, \
    including 1 "Number 100: Numeron Dragon". (Transfer its materials to this card.) \
This card's Special Summon cannot be negated. \
You can only control 1 "{CARD_NAME}". \
Your opponent cannot Tribute this card, or use it as material for an Summon. \
Its battle position cannot be changed by card effects. \
Its control cannot switch. \
The above effects cannot be negated or be copied. \
Cannot be destroyed by battle, except with an "Number" monster. \
This card gains the original effects of all "Number" Xyz Monsters \
    that has a number between "1" and "100" in its name attached to this card, \
    except "{CARD_NAME}". \
"""
strings = []

[icxyz-barian-hope-emperor]
id = 900004002
rarity = "gold"
name = "iCxyz Barian Hope Emperor"
set = "cxyz chaos barian"
type = "monster xyz effect"
attribute = "light"
race = "warrior"
rank = 8
atk = 0
def = 0
effect = """\
4 or more Level 8 monsters
Must be Xyz Summoned. \
This card's Special Summon cannot be negated. \
You can only control 1 "{CARD_NAME}". \
Your opponent cannot Tribute this card, or use it as material for an Summon. \
Its battle position cannot be changed by card effects. \
Its control cannot switch. \
If this card is Xyz Summoned by using "Cxyz Barian Hope" as material, \
    this card gains its original effects. \
The above effects cannot be negated or be copied. \
If this card has "Cxyz Barian Hope" as an material, it gains this effect.
● The effects of this card, "Number C", "Barian's", and "Seventh" card you control cannot be negated.
● This card gains the original effects of all "Number C" Xyz Monsters \
    that has a number between "101" and "107" in its name attached to this card, \
    also their's name is also treated as their orginal number.
● If you would detach an material(s) from this card, you can pay 800 LP instead.
"""
strings = []

[full-armored-silent-honor-dark]
id = 900004003
name = "Number C101: Full Armored Silent Honor DARK"
set = "number-c chaos"
type = "monster xyz effect"
attribute = "water"
race = "aqua"
rank = 6
atk = 2800
def = 1500
effect = """\
4 Level 6 WATER monsters
You can also Xyz Summon this card \
    by sending 1 WATER Xyz Monster from your Extra Deck to the GY, \
    then using by using 1 Rank 5 or 6 WATER Xyz Monster you control as material. \
    (Transfer its materials to this card.) \
While there is a WATER Xyz Monster in your GY, \
    your opponent cannot target this card with card effects, \
    also it cannot be destroyed, or banished, by card effects. \
Once per turn: You can target 1 other face-up monster on the field \
    or 1 face-up Spell/Trap Card in your banishment; \
    detach 1 material from a monster you control, and if you do, \
    equip the targeted card to this card as an Equip Spell that gives it 1200 ATK. \
Once per turn, during the End Phase: \
    Attach all Equip Cards equipped to this card to it as material, \
    then destroy cards on the field, up to the number attached. \
"""
strings = [
    "Xyz Summon by using a Rank 5 or 6 WATER Xyz Monster",
    "Equip 1 other card",
    "Attach all equipped cards",
]
