[numeron-genesis-dragon]
id = 900004001
rarity = "gold"
name = "Numeron Genesis Dragon"
set = "numeron"
type = "monster xyz effect"
attribute = "divine"
race = "dragon"
rank = 13
atk = 0
def = 0
effect = """\
Cannot be Xyz Summoned. \
Must be Special Summoned (from your Extra Deck) by overlaying all Xyz Monsters you control, \
    including 1 "Number 100: Numeron Dragon". (Transfer its materials to this card.) \
This card's Special Summon cannot be negated. \
You can only control 1 "{CARD_NAME}". \
Your opponent cannot Tribute this card, or use it as material for an Summon. \
Its battle position cannot be changed by card effects. \
Its control cannot switch. \
The above effects cannot be negated or be copied. \
Cannot be destroyed by battle, except with an "Number" monster. \
This card gains the original effects of all "Number" Xyz Monsters \
    that has a number between "1" and "100" in its name attached to this card, \
    except "{CARD_NAME}". \
"""
strings = []

[icxyz-barian-hope-emperor]
id = 900004002
rarity = "gold"
name = "iCxyz Barian Hope Emperor"
set = "cxyz chaos barian"
type = "monster xyz effect"
attribute = "light"
race = "warrior"
rank = 8
atk = "?"
def = "?"
effect = """\
4 or more Level 8 monsters
Must be Special Summoned with a "Rank-Up-Magic" Spell targeting "Cxyz Barian Hope". \
This card's Special Summon cannot be negated. \
You can only control 1 "{CARD_NAME}". \
Your opponent cannot Tribute this card, or use it as material for an Summon. \
Its battle position cannot be changed by card effects. \
Its control cannot switch. \
This card's original ATK/DEF are equal to the number of materials attached to it x 1000. \
The above effects cannot be negated or be copied. \
This card gains the original effects of all "Number C" Xyz Monsters \
    that has a number between "101" and "107" in its name attached to this card. \
If this card has "Cxyz Barian Hope" as an material, it gains this effect.
● If you would detach an material(s) from this card, you can pay 800 LP instead.
● This card cannot be destroyed, or banished, by card effects, \
    also your opponent cannot target it with card effects.
"""
strings = []
