[numeron-code]
id = 900004000
alias = 41418852
rarity = "gold"
name = "Numeron Code"
type = "spell field"
effect = """
This card's name is always treated as "Numeron Network".)
The activation of this card, or its effects, cannot be negated, or can its effects be negated. \
Cannot be targeted by card effects. \
Special Summons of your "Number" Xyz Monsters cannot be negated. \
"Numeron" Xyz Monsters you control can activate effects without detaching material(s). \
(Quick Effect): You can send 1 "Numeron" Spell/Trap Card from your hand or Deck to the GY; \
    pay that card activation costs and this effect becomes that card's effect when that card is activated. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = ["Send 1 \"Numeron\" Spell/Trap to GY and activate its effect"]

[numeron-code-dragon]
id = 900004001
rarity = "gold"
name = "Numeron Code Dragon"
set = "numeron"
type = "monster xyz effect"
attribute = "divine"
race = "dragon"
rank = 1
atk = 0
def = 0
effect = """\
Cannot be Xyz Summoned. \
Must be Special Summoned (from your Extra Deck) by overlaying all "Number" Xyz Monsters you control, \
    including 1 monster with original name is "Number 100: Numeron Dragon". \
    (Transfer its materials to this card.) \
This card's Special Summon cannot be negated. \
You can only control 1 "{CARD_NAME}". \
Your opponent cannot Tribute this card, or use it as material for an Summon. \
Its battle position cannot be changed by card effects. \
Its control cannot switch. \
The above effects cannot be negated or be copied. \
Cannot be destroyed by battle, except with an "Number" monster. \
Once per Chain, if an "Number" monster(s) that has a number between "1" and "100" \
    is Special Summoned to your field (except during the Damage Step): \
    You can target those monsters; attach them to this card as material. \
This card gains the original effects of all "Number" Xyz Monsters \
    that has a number between "1" and "100" in its name attached to this card. \
"""
strings = ["Attach Special Summoned monsters to this card"]

[numeron-summon-revision]
id = 900004002
name = "Numeron Summon Revision"
set = "numeron"
type = "trap counter"
effect = """
"""
strings = []

[numeron-magic-revision]
id = 900004003
name = "Numeron Magic Revision"
set = "numeron"
type = "trap counter"
effect = """
When your opponent activates a Spell Card or effect, \
    while you control no other Spell/Trap Cards, except "Numeron Network": \
    Reveal 1 Spell with different name that card, and meets its activation conditions, \
    the activated effect becomes the revealed card's effect. \
    Send the revealed card to the GY. \
You can only activate 1 "{CARD_NAME}" per turn. \
"""
strings = []
