[numeron-code-dragon]
id = 900004001
rarity = "gold"
name = "Numeron Code Dragon"
set = "numeron"
type = "monster xyz effect"
attribute = "divine"
race = "dragon"
rank = 13
atk = 0
def = 0
effect = """\
Cannot be Xyz Summoned. \
Must be Special Summoned (from your Extra Deck) by overlaying all Xyz Monsters you control, \
    including 1 "Number 100: Numeron Dragon". (Transfer its materials to this card.) \
This card's Special Summon cannot be negated. \
You can only control 1 "{CARD_NAME}". \
Your opponent cannot Tribute this card, or use it as material for an Summon. \
Its battle position cannot be changed by card effects. \
Its control cannot switch. \
This card gains the original effects of all "Number" Xyz Monsters \
    that has a number between "1" and "100" in its name attached to this card, \
    except "{CARD_NAME}". \
Cannot be destroyed by battle, except with an "Number" monster. \
The above effects cannot be negated or be copied. \
"""
strings = []
