[numeron-genesis-dragon]
id = 900004001
rarity = "gold"
name = "Numeron Genesis Dragon"
set = "numeron"
type = "monster xyz effect"
attribute = "divine"
race = "dragon"
rank = 13
atk = 0
def = 0
effect = """\
Cannot be Xyz Summoned. \
Must be Special Summoned (from your Extra Deck) by overlaying all Xyz Monsters you control, \
    including 1 "Number 100: Numeron Dragon". (Transfer its materials to this card.) \
This card's Special Summon cannot be negated. \
You can only control 1 "{CARD_NAME}". \
Your opponent cannot Tribute this card, or use it as material for an Summon. \
Its battle position cannot be changed by card effects. \
Its control cannot switch. \
The above effects cannot be negated or be copied. \
Cannot be destroyed by battle, except with an "Number" monster. \
This card gains the original effects of all "Number" Xyz Monsters \
    that has a number between "1" and "100" in its name attached to this card, \
    except "{CARD_NAME}". \
"""
strings = []

[icxyz-barian-hope-emperor]
id = 900004002
rarity = "gold"
name = "iCxyz Barian Hope Emperor"
set = "cxyz chaos barian"
type = "monster xyz effect"
attribute = "light"
race = "warrior"
rank = 8
atk = 0
def = 0
effect = """\
4 or more Level 8 monsters
Must be Xyz Summoned. \
This card's Special Summon cannot be negated. \
You can only control 1 "{CARD_NAME}". \
Your opponent cannot Tribute this card, or use it as material for an Summon. \
Its battle position cannot be changed by card effects. \
Its control cannot switch. \
If this card is Xyz Summoned by using "Cxyz Barian Hope", \
    this card gains its original effects. \
The above effects cannot be negated or be copied. \
If this card has "Cxyz Barian Hope" as an material, it gains this effect.
● The effects of this card, "Barian's" Spell/Trap and "Seventh" Spell/Trap you control cannot be negated.
● This card gains the original effects of all "Number C" Xyz Monsters \
    that has a number between "101" and "107" in its name attached to this card.
● If you would detach an material(s) from this card, you can pay 800 LP instead.
"""
strings = []
